### ISSUE TITLE
Stock Financials Data Outdated

### ISSUE THREAD

**Issue by Nachtel** [polygon-io/client-python#102]
When using `client.reference_stock_financial("AAPL")`, as recent as it will go is March of 2020 regardless of ticker. I'd like to be able to use more recent data, including all of 2021.

**Comment by secondvibe** [comment]
Looks like it is not pointing to the latest API endpoint: https://github.com/polygon-io/client-python/blob/master/polygon/rest/client.py#L82 - I believe it should be /vX/reference/financials

No one from polygon maintaining this package?

**Comment by matichenor** [comment]
We are working on a major update to this client which will address this issue.

**Comment by matichenor** [comment]
Closing this ticket to consolidate and track it in https://github.com/polygon-io/client-python/issues/109
