### ISSUE TITLE
signal only works in main thread

### ISSUE THREAD

**Issue by KumarRupesh** [polygon-io/client-python#103]
Hi,
I am trying to implement polygon WebSocketClient in Django framework.  The sample code shared with us gives an error:

signal only works in main thread

on below line of code:

my_client = WebSocketClient(STOCKS_CLUSTER, key, my_custom_process_message)

Please let me know if you have some suggestions to resolve this.

Thank you!
Kumar Rupesh

**Comment by matichenor** [comment]
Unfortunately I don't think we have enough detail to help out on this one.  Please feel free to reach out to us on slack, ping us on our website chat feature, or raise a new ticket with more detail.

Closing this one for now.
