### ISSUE TITLE
Options data not coming through websocket connection?

### ISSUE THREAD

**Issue by MLTQ** [polygon-io/client-python#105]
Hello,
I have a subscription to the options feed and am trying to set up an object to handle the websocket and output thereof. This is just debugging right now, and it appears to subscribe successfully but nothing ever comes through the socket itself. As you can see in the screenshot, I've tried several permutations of the option format to subscribe, which all work, and none of which produce results. 

Expected behavior: it starts streaming output to the process_message function, whereupon I can operate with it. 
```
class option_world:
    #This is a class to handle a websocket connection and a "world" of stocks with continual update.
    #Will be fleshed out once we have the websocket api
    def __init__(self, key, targets, debug=False):
        def process_message(message):
            print("websocket output:", message)
        self.key = key
        self.client = polygon.WebSocketClient('options', key, process_message)

        self.client.run_async()
        self.debug = debug
        if self.debug:
            self.verbose = True
        else:
            self.verbose = False
        for target in targets:
            self.client.subscribe(f'T.{target}')
```
        

![image](https://user-images.githubusercontent.com/58714428/158648697-560dd559-568a-4f6f-a98d-57015bedd871.png)

**Comment by matichenor** [comment]
We're not aware of an issue with the options APIs.  We'll take a look at your code to see if we help troubleshoot!

**Comment by matichenor** [comment]
Hi @MLTQ , I reworked your code to demonstrate a few calls which should work.  The problems are that:
1. We don't currently support subscribing to an options feed by underlying ticker.
2. Polygon options contracts tickers are prefix with "O:".  Your options tickers are missing that.  I realize this isn't clear in our doc and I'll make a ticket to update the doc.

`
import polygon

def my_custom_process_message(message):
    print("this is my custom message processing", message)


def process_message(message):
    print("websocket output:", message)
key = "XXX"
client = polygon.WebSocketClient('options', key, process_message)

client.run_async()

targets = ["O:AAPL220318C00157500", "O:AAPL220318C00160000", "O:AAPL220318C00162500"]

for target in targets:
    print("Subscribing to trade feed for {0}".format(target))
    client.subscribe(f'T.{target}')
`

**Comment by MLTQ** [comment]
Alright- sad that that endpoint doesn't work, but your fix does!  Thank you!
