### ISSUE TITLE
Timestamps of "Live" options flow are ~2-8 hours behind

### ISSUE THREAD

**Issue by MLTQ** [polygon-io/client-python#110]
Hi, I have the options show websocket hooked up and processing incoming data into a postgres database. 
The handler is extremely small:
`    
    class option_world:

        def __init__(self, key, targets, debug=False):
            def process_message(message):

                print("websocket output:", message)
                message = ast.literal_eval(message)
                for block in message:
                    price = block['p']
                    occured = block['t']
                    size = block['s']

                    op = option(block['sym'], price, size, occured)
                    insert_option(op.ticker, op)

            self.key = key
            self.client = polygon.WebSocketClient('options', key, process_message)
            self.options = []
            self.client.run_async()
            self.debug = debug`
and the `option` class is really just a dictionary at this point. Minimal processing on my side. 

When watching the output, I see the timestamps (`t`)are often ~2hrs in the past, and come in for some time even after market close. 

According to your docs, if the client side is slow, it should outputting the websocket message to a list, which does happen occasionally (hence the `for block in message`),  but the vast majority of hits are single messages. 
Why is this system so slow? Is this a client side problem or server side? And how can I speed it up to get truly live data?

**Comment by matichenor** [comment]
Hi @MLTQ , what are you subscribing to in the above?  Have you tried subscribing to just a single symbol to see if you continue to face the processing delays?

**Comment by MLTQ** [comment]
Currently we're subscribing to all contracts from SPY, AAPL, and TSLA for testing. I have reduced it to just all from SPY to test exactly this and the problem remains

**Comment by matichenor** [comment]
@MLTQ ,

On Polygon's side if your code does not process packets as fast as we are sending them, we will begin to buffer messages. 
 Eventually if this buffer is not emptying quickly enough messages will drop and can result in the long time that you described.
 
You can validate your buffer status on the Polygon Dashboard.  Navigate to Connections -> (Select the active connection from the table) 

You will see a chart that gives you an idea of the buffer size:
<img width="552" alt="Screen Shot 2022-05-18 at 1 39 50 PM" src="https://user-images.githubusercontent.com/7317407/169107340-aab0eb5f-fd3a-453b-a0bf-70bfd6b6a04a.png">\

**Comment by matichenor** [comment]
At this time we're not seeing any delays with our options data on websocket or REST.  If you are still seeing a problem, can you please reach out to our developer relations team either through the chat on https://polygon.io/ or at [support@polygon.io](mailto:support@polygon.io) .  I think we will better be able to address this through a conversation there than this github issue.
