### ISSUE TITLE
Websocket and Websocket-client are needed to initialize the client so why aren't these packages requirements in this project?

### ISSUE THREAD

**Issue by PyDataBlog** [polygon-io/client-python#13]
One cannot use the client class without having `websocket` and `websocket-client` installed so why aren't these packages dependencies for the package? It would make life easier for everyone. ie #12

**Comment by jbonzo** [comment]
that was most likely an oversight. I will correct that in a future PR, which I will link here

**Comment by jbonzo** [comment]
@PyDataBlog I am going to mark this as closed. If other dependency related issues arise please create a new issue.
