### ISSUE TITLE
Is it possible to save the streaming data?

### ISSUE THREAD

**Issue by PyDataBlog** [polygon-io/client-python#15]
Using this client, is it possible to save streaming data?

**Comment by jbonzo** [comment]
Can you provide some more context? What exactly do you mean by save the data?

**Comment by PyDataBlog** [comment]
Just storing the incoming stream data in a variable and process it after the connection has been terminated.

**Comment by jbonzo** [comment]
Sure it's very possible. The design for the WebSocketClient is based around defining your own event handlers. You can define your own handler that saves the data to a scoped variable and then do whatever you want with that variable. You could also implement database logic in your handler and directly stream data into your own database solution.
Here is an example of a customer handler that takes in a list and adds to that list for every 
```python
import time
from typing import List

from polygon import WebSocketClient, STOCKS_CLUSTER


def my_custom_process_message(messages: List[str]):
    def add_message_to_list(message):
        messages.append(message)

    return add_message_to_list


def main():
    key = 'your api key'
    messages = []
    my_client = WebSocketClient(STOCKS_CLUSTER, key, my_custom_process_message(messages))
    my_client.run_async()

    my_client.subscribe("T.MSFT", "T.AAPL", "T.AMD", "T.NVDA")
    time.sleep(1)

    my_client.close_connection()
    
    for message in messages:
        # process messages
        pass


if __name__ == "__main__":
    main()

```
