### ISSUE TITLE
When getting results from get_aggs, when there are no results an exception is thrown instead of returning None

### ISSUE THREAD

**Issue by pushshift** [polygon-io/client-python#180]
It looks like a results key is expected even if there is a chance that none is returned. This may be a bug on Polygon's API side in that they probably should be returning an empty results key instead of none at all. 

Fix might be to check if 'results' exists in the return?

```
Traceback (most recent call last):
  File "/opt/polygon/./ingest.py", line 146, in <module>
    get_agg_history(ticker="INTC")
  File "/opt/polygon/./ingest.py", line 70, in get_agg_history
    aggs = client.get_aggs(ticker=ticker, from_=start_date, to=end_date, multiplier=1, timespan="minute")
  File "/usr/local/lib/python3.10/dist-packages/polygon/rest/aggs.py", line 45, in get_aggs
    return self._get(
  File "/usr/local/lib/python3.10/dist-packages/polygon/rest/base.py", line 82, in _get
    obj = obj[result_key]
KeyError: 'results'
```

**Comment by tomadec** [comment]
hi, sorry I am quite new to python. Having the same error message in my code:
  File "/Users/xxx/PycharmProjects/pythonProject3/main.py", line 246, in <module>
    main()
  File "/Users/xxx/PycharmProjects/pythonProject3/main.py", line 225, in main
    print(client.get_daily_open_close_agg(Option_index, Date))
  File "/Users/xxx/Library/CloudStorage/OneDrive-Personal/pythonProject3/lib/python3.8/site-packages/polygon/rest/aggs.py", line 156, in get_daily_open_close_agg
    return self._get(
  File "/Users/xxx/Library/CloudStorage/OneDrive-Personal/pythonProject3/lib/python3.8/site-packages/polygon/rest/base.py", line 129, in _get
    raise BadResponse(resp.data.decode("utf-8"))
polygon.exceptions.BadResponse: {"status":"NOT_FOUND","request_id":"910041197e72160f218d1a11fad9cacd","message":"Data not found."}

how can I avoid stopping my code when this error occurs and move to the next symbol in my list of Option_index?

**Comment by justinpolygon** [comment]
Hey @tomadec,

To avoid stopping your code when the polygon.exceptions.BadResponse error occurs and continue with the next symbol in your list of Option_index, you can use a try-except block around the code that might raise the exception. The try-except block will catch the exception and allow you to handle it gracefully, such as by logging the error and moving on to the next iteration of your loop.

Here's how you could modify your example to include error handling:

```python
from polygon import RESTClient

client = RESTClient()  # POLYGON_API_KEY environment variable is used

# Assuming you have a list of option symbols and dates to iterate through
option_symbols = ["O:SPY251219C00650000", "O:AnotherSymbolHere"]  # Example list of option symbols
date = "2023-02-22"  # Example date

for symbol in option_symbols:
    try:
        # Attempt to get daily open-close aggregation for the current option symbol on the given date
        request = client.get_daily_open_close_agg(symbol, date)
        print(f"Data for {symbol}: {request}")
    except polygon.exceptions.BadResponse as e:
        # Handle the error: log it, print a message, etc.
        print(f"Error fetching data for {symbol} on {date}: {e}")
        # Continue to the next symbol without stopping the program
        continue
```

Cheers & hope that helps!

**Comment by tomadec** [comment]
Thks so much, very clear and helpfull! Works as expected.Thomas DecouvelaereLe 21 févr. 2024 à 21:49, justinpolygon ***@***.***> a écrit :﻿
Hey @tomadec,
To avoid stopping your code when the polygon.exceptions.BadResponse error occurs and continue with the next symbol in your list of Option_index, you can use a try-except block around the code that might raise the exception. The try-except block will catch the exception and allow you to handle it gracefully, such as by logging the error and moving on to the next iteration of your loop.
Here's how you could modify your example to include error handling:
from polygon import RESTClient

client = RESTClient()  # POLYGON_API_KEY environment variable is used

# Assuming you have a list of option symbols and dates to iterate through
option_symbols = ["O:SPY251219C00650000", "O:AnotherSymbolHere"]  # Example list of option symbols
date = "2023-02-22"  # Example date

for symbol in option_symbols:
    try:
        # Attempt to get daily open-close aggregation for the current option symbol on the given date
        request = client.get_daily_open_close_agg(symbol, date)
        print(f"Data for {symbol}: {request}")
    except polygon.exceptions.BadResponse as e:
        # Handle the error: log it, print a message, etc.
        print(f"Error fetching data for {symbol} on {date}: {e}")
        # Continue to the next symbol without stopping the program
        continue
Cheers & hope that helps!
