### ISSUE TITLE
Ticker News Api issue

### ISSUE THREAD

**Issue by ehtycuact** [polygon-io/client-python#196]
https://github.com/polygon-io/client-python/blob/aa4f2097bc700ec0c320e81030ca1aefcd94807c/polygon/rest/base.py#L141

This line actually changes the whole `published_utc_lt` to `published.utc.lt` so the api call does not work properly and does not take into account the date filter.

**Comment by matichenor** [comment]
Thanks for raising this issue! We're taking a look.

**Comment by clickingbuttons** [comment]
Good catch! Will fix and release a new version ASAP.
