### ISSUE TITLE
error on websocket example

### ISSUE THREAD

**Issue by nkchem09** [polygon-io/client-python#209]
**Describe the bug**

windows 10
python3.9
polygon.__version__
Out[2]: '1.0.0b15'

running examples\websocket\crypto.py:
Traceback (most recent call last):

  File "D:\worksPool\client-python-master\examples\websocket\crypto.py", line 13, in <module>
    c.run(handle_msg)

  File "d:\ProgramData\Anaconda3\lib\site-packages\polygon\websocket\__init__.py", line 168, in run
    asyncio.run(self.connect(handle_msg_wrapper, close_timeout, **kwargs))

  File "d:\ProgramData\Anaconda3\lib\asyncio\runners.py", line 33, in run
    raise RuntimeError(

RuntimeError: asyncio.run() cannot be called from a running event loop
**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by clickingbuttons** [comment]
I installed [Python 3.9.13](https://www.python.org/downloads/release/python-3913/) on a Windows 10 machine and was unable to reproduce with `polygon-api-client==1.0.2`.

Looking at your stack trace further it looks like you're using an Anaconda asnycio runner (`d:\ProgramData\Anaconda3\lib\asyncio\runners.py`). I'm not familiar with how Anaconda works, but I'd try getting it to use the standard python runner or installing `polygon-api-client` without Anaconda.

**Comment by nkchem09** [comment]
Thank you for your help.
