### ISSUE TITLE
"historic_n___bbo_quotes_v2" function name

### ISSUE THREAD

**Issue by blankbits** [polygon-io/client-python#21]
Does the following user-facing function intentionally include three consecutive underscores? Just a quick note that this may be in error. Thanks for the great product!

https://github.com/polygon-io/client-python/blob/02c61940542e86cce086d32c69006ec2a3e2980c/polygon/rest/client.py#L89

**Comment by sarah13889** [comment]
I am getting the same error

**Comment by blankbits** [comment]
Thanks for the reply! The functionality is working as expected for me, so
not in urgent need of a change, just wanted to call this out since it
looked odd. Thank you for building a great product.
