### ISSUE TITLE
reference_tickers method doesn't populate its self.symbol attribute

### ISSUE THREAD

**Issue by junseoky21** [polygon-io/client-python#22]
.reference_tickers() method doesn't populate its self.symbol attribute

**JSON Example of self.resp.reference_tickers(page=1,search="microsoft"):**
{'page': 1, 'perPage': 50, 'count': 2, 'status': 'OK', 'tickers': [{'ticker': 'MSFT', ..., 'url': 'https://api.polygon.io/v2/tickers/MSF'}]}
**Returns a ReferenceTickersApiResponse** 

I found ReferenceTickersApiResponse class has its only member "symbol" for parsing the json result in List of Symbol class. Since returned JSON is in dictionary, not a list, it parses the keys from the dictionary to be its attribute and not filling in the "symbol" attribute (I believe the "symbol" attribute was meant to parse the "ticker" key from the json dictionary).
Then, If you try to access its only attribute "symbol", you get an attribute error.

**Comment by junseoky21** [comment]
Traceback (most recent call last):
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\junse\source\repos\trdr\trader_main\views.py", line 293, in index
    dm.polytest()
  File "C:\Users\junse\source\repos\trdr\trader_main\views.py", line 49, in polytest
    print(ticker_res.symbol)
AttributeError: 'ReferenceTickersApiResponse' object has no attribute 'symbol'

**Comment by matichenor** [comment]
Hey, thanks for raising this issue and our apologies for our slow response.

We have released a new version our client that should address this issue.  You can use the new client by installing it through pip:
`pip install polygon-api-client~=1.0.0b`

If you find any issues with the new version we would love to hear your feedback! Thanks!
