### ISSUE TITLE
Is /v1/last/crypto/{from}/{to} supported

### ISSUE THREAD

**Issue by nodesocket** [polygon-io/client-python#222]
**Is your feature request related to a problem? Please describe.**
I was not able to determine if last trade for a crypto pair is supported in this client lib. Is `/v1/last/crypto/{from}/{to}` supported?

If so, would you mind showing an example? Thanks.

**Comment by morningvera** [comment]
Hey @nodesocket, this is supported and is documented [here](https://polygon-api-client.readthedocs.io/en/latest/Trades.html#get-last-crypto-trade)!
