### ISSUE TITLE
Filter Extensions Do Not Appear to Work in the list_options_contracts API

### ISSUE THREAD

**Issue by wwashington** [polygon-io/client-python#242]
**Describe the bug**

I am unable to get any of the filter extensions to work in the list_options_contracts API.

**To Reproduce**

```
options = []

query_params = {'underlying_ticker' : 'AMZN',
                'contract_type' : 'call',
                'expiration_date.lte' : '2022-08-19'}

for o in client.list_options_contracts(**query_params):
    options.append(o)
    

print(options)
```

generates the following error:

```
Traceback (most recent call last):
  File "/Users/winefred/OptBot/src/simple-get.py", line 17, in <module>
    for o in client.list_options_contracts(**query_params):
TypeError: list_options_contracts() got an unexpected keyword argument 'expiration_date.lte'
```

If I drop the '.lte', the query works as expected, and the API returns all options with expiration date equal to the date; however, I would like the results with all dates prior to and including the date specified.

**Comment by clickingbuttons** [comment]
Try `expiration_date_lte` instead of `expiration_date.lte`. Variable names can't contain `.` in Python.

**Comment by clickingbuttons** [comment]
I believe this was just a typo. Closing.
