### ISSUE TITLE
BRK.B not supported in WebSockets

### ISSUE THREAD

**Issue by Stormy110** [polygon-io/client-python#282]
**Describe the bug**
When using the Python SDK to connect to BRK.B quotes, I receive the following error - error: Message: 'invalid subscription:' Arguments: ('Q.BRK.B',)

When connecting to Q.*, BRK.B is returned successfully. 

[{"ev":"Q","sym":"BRK.B","c":1,"i":[1,605],"bx":12,"ax":9,"bp":304.57,"ap":304.64,"bs":1,"as":1,"t":1660755007192,"q":32092505,"z":1}]

**To Reproduce**
Connect to the WebSockets using the Python example and try to stream Q.BRK.B

**Comment by Darcy-Linde** [comment]
I ran the websocket aggs.py example with a subscription to "Q.BRK.B" and had no error. Are you able to provide a stack trace or code snippet?
