### ISSUE TITLE
Limit Parameter for list_quotes does not work

### ISSUE THREAD

**Issue by Mcrob1989** [polygon-io/client-python#285]
**Describe the bug**
The Limit Parameter for list_quotes does not work.  This parameter seems to be ignored and all quotes matching the other parameter inputs are returned.

**To Reproduce**
1. Run the following code after input the proper api information.

`from polygon import RESTClient

client = RESTClient()
		
trades = []
for t in client.list_quotes('QQQ', '2022-01-04', limit=1):
	print(t)`

**Expected behavior**
Only one quote would be printed.

**Actual behavior**
A large series of quotes are printed.

**Comment by clickingbuttons** [comment]
This is intended. The `limit` field just determines the page size used when iterating. If you truly want only one quote, simply break in the loop like this:
```py
from polygon import RESTClient

client = RESTClient()

trade = None
for t in client.list_quotes('QQQ', '2022-01-04', limit=1):
  trade = t
  break

print(t)
```

**Comment by Mcrob1989** [comment]
I guess I was just a little thrown off by the description which states:

> :param limit: Limit the number of results returned, default is 10 and max is 50000.

I took this to mean that it would only return a maximum number of results based on the limit provided.

**Comment by clickingbuttons** [comment]
That's true for `get_*` methods. For `list_*` methods it's the page size when iterating. I agree with you that we should update the docs for `list_*` to be clear it changes the page size.

**Comment by Mcrob1989** [comment]
Thanks for all the great info and quick responses!
