### ISSUE TITLE
Subscriptions are not changed until a message from existing subscription is received

### ISSUE THREAD

**Issue by at-cf** [polygon-io/client-python#293]
In __init__.py of websocket, it would be better like this (commented the original incorrect line):

```python
                    try:
                        # cmsg: Union[
                        #     List[WebSocketMessage], Union[str, bytes]
                        # ] = await s.recv()
                        cmsg: Union[
                            List[WebSocketMessage], Union[str, bytes]
                        ] = await asyncio.wait_for(s.recv(), timeout=1)
                    except asyncio.TimeoutError:
                        continue
```

Imagine a case where someone is subscribed to trades on an illiquid instrument. So maybe it takes 5-10 minutes before a trade message received. If they try to change the active subscriptions, no error is raised, but silently, no actual change in subscription has ocurred until there's a trade on that illiquid instrument.

**Comment by clickingbuttons** [comment]
Good call. Feel free to open a PR in the future.
