### ISSUE TITLE
Polygon 2 decimals vs TD Ameritrade has 4 

### ISSUE THREAD

**Issue by mbvg1** [polygon-io/client-python#299]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by clickingbuttons** [comment]
This is an API issue, not a client issue. Moving.

**Comment by clickingbuttons** [comment]
Looks like I can't move it, please reopen in https://github.com/polygon-io/issues .
