### ISSUE TITLE
Simple REST Demo returns bad request

### ISSUE THREAD

**Issue by isayahc** [polygon-io/client-python#30]
i copy and pasted the code adding my key. However it returned "requests.exceptions.HTTPError: 400 Client Error: Bad Request for url" When i clicked the URL. The JSON object said "error :"today's date not supported yet" ".

**Comment by isayahc** [comment]
The issue was the date format. 
```
resp = client.stocks_equities_daily_open_close("AAPL", "2018-3-2")
```
should be 
```
resp = client.stocks_equities_daily_open_close("AAPL", "2018-03-02")
```

**Comment by xrl** [comment]
This would be great as a PR to the README, @jbonzo what do you think?
