### ISSUE TITLE
Allow user to specify json module

### ISSUE THREAD

**Issue by at-cf** [polygon-io/client-python#305]
Python default json module is slow, there are faster third-party alternatives that follow the same interface as json.dumps/loads (sometimes 5x-10x faster).

It's common for JSON-intensive libraries to allow a user to specify a json module as argument (override the default json module.)

This would be very beneficial for socket apps that are parsing hundreds of requests per second.

**Comment by clickingbuttons** [comment]
If lightweight enough this sounds like a reasonable default. PR welcome, likely won't prioritize this for months.

**Comment by clickingbuttons** [comment]
Closed in #306.
