### ISSUE TITLE
Tick Data Example

### ISSUE THREAD

**Issue by sarah13889** [polygon-io/client-python#33]
I am trying to extract Tick data in python and save the file, is there an example please?
I tried the Demo for Rest API and changed the daily into NBBO yet i am getting an error.

**Comment by bryanbmb** [comment]
@sarah13889 Hi did you find a way yet? I've been trying to figure out the same.

**Comment by sarah13889** [comment]
Hey @bryanbmb, no I had to use the requests.get(url) Instead. 
![264D50F6-4EF0-42BF-BCF2-CEDFC7053B81](https://user-images.githubusercontent.com/58334199/90222176-d7844d80-de0b-11ea-9f6b-d2a33d6d53b7.jpeg)

Now i am facing a problem saving the json file, maybe bec of format of the data inside it.

**Comment by dyu41** [comment]
did you try 
client = RESTClient(API_KEY)
client.historic_trades_v2(..)

**Comment by matichenor** [comment]
We have a new version of the library with improved documentation and sample code that should help you here!

See the [Getting Started](https://polygon-api-client.readthedocs.io/en/latest/Getting-Started.html) section in our docs or view the [examples](https://github.com/polygon-io/client-python/blob/master/examples) directory.
