### ISSUE TITLE
Websocket connection closed premarturely

### ISSUE THREAD

**Issue by tmilian** [polygon-io/client-python#34]
Hi guys !

I have encountered an error when I tried to connect to any websocket endpoint through this library.

`self.ws_client = WebSocketClient(STOCKS_CLUSTER, token, self.__streaming_callback)`
`self.ws_client.run_async()`
`self.ws_client.subscribe("A.AAPL")`
`time.sleep(2)`
`self.ws_client.close_connection()`

Right after the call to 'subscribe' method the connection was closed without showing any error.

An SSL certificate error ? 
Tell me if it's a bad use on my side or if my fix is right, I managed the issue by replacing line 47 in your websocket_client.py file with this :

`self.ws.run_forever(sslopt={"cert_reqs": ssl.CERT_NONE})`

Don't forget to import ssl in the file.

Cheers !

**Comment by matichenor** [comment]
Closing this issue out as it's rather old.  If you're still having a problem and want some help, reach out to us on the community slack, through our in-website chat, or by raising a new issue here.
