### ISSUE TITLE
Requirements are too strict

### ISSUE THREAD

**Issue by Rizhiy** [polygon-io/client-python#35]
I noticed that the package on pip specifies all requirements with exact versions.
This is quite annoying since it greatly increases probability of conflicts (which I now encountered).

Could you please relax the requirements? Ideally only specify the minimum version.

**Comment by Rizhiy** [comment]
@jbonzo Yes, that looks great. Just check that it works with fresh install, in case some packages released braking changes.

**Comment by Rizhiy** [comment]
@jbonzo Actually, I just checked the new version and it appears that you have mismatch of requirements.
During install requirements are taken from `setup.py` and `requirements.txt` appears useless.
Sorry for the confusion.

P.S. at present `requirements.txt` is not used anywhere, maybe should get rid of it.

**Comment by Rizhiy** [comment]
I have created a merge request: #38

**Comment by Rizhiy** [comment]
You should probably change to have a single source of requirements, since I see that your `tox.ini` uses  `requirements.txt` while `setup.py` uses it's own.

**Comment by jbonzo** [comment]
I don't believe we need to prune back to one document of requirements. [This section](https://packaging.python.org/discussions/install-requires-vs-requirements/#requirements-files) suggests that `requirements.txt` and `install_require` server different purposes, where `requirements.txt` illustrates whats needed for a full working dev environment. Currently `tox.ini` is not a critical part of this repo, but it is used for development so I think its dependency on `requirements.txt` is desired.

Please let me know if you think I am misunderstanding these concepts.

**Comment by Rizhiy** [comment]
Yes, that is correct, although usually to avoid duplication one should inherit from another, e.g. `requirements.txt` can use `-e .` to include the package itself and minimal requirements.
Although I'm not sure whether tox can parse that.

I think the MR should resolve the issue, I will close it once package is updated on pip.
