### ISSUE TITLE
GroupedDailyAggs in crypto

### ISSUE THREAD

**Issue by alexcstark** [polygon-io/client-python#351]
**Is your feature request related to a problem? Please describe.**
I want to query grouped daily aggs for crypto but am unable to because locale in the method is hardcoded to "us" and cannot be changed to global. As a result, I have custom code to support this.

**Describe the solution you'd like**

Allow passing of locale to `get_grouped_daily_aggs` or set locale to global if `market_type` is crypto

**Describe alternatives you've considered**

I have my own client lib but I don't want to maintain it. 

**Additional context**

**Comment by antdjohns** [comment]
@alexcstark just released a patch for this issue. Let us know if there is anything else.

**Comment by antdjohns** [comment]
Patched.
