### ISSUE TITLE
AttributeError: 'RESTClient' object has no attribute 'get_ticker_details'

### ISSUE THREAD

**Issue by adityakalkote** [polygon-io/client-python#358]
from polygon import RESTClient

client = RESTClient()

financials = client.get_ticker_details("NFLX")
print(financials)

**Comment by antdjohns** [comment]
Hey @adityakalkote are you passing an argument for your api_key when initializing the client?

also are you using the latest version of our api? I am not able to reproduce this error. I am getting a response and get_ticker_details is present as a property of the rest client.

**Comment by antdjohns** [comment]
@adityakalkote here is a reference to our [README](https://github.com/polygon-io/client-python/blob/master/README.md), please let me know if you have any other issues.

**Comment by antdjohns** [comment]
Closed Issue. No response.
