### ISSUE TITLE
Some Keys like 'market_cap' not available using get_ticker_details for 01-18-2023

### ISSUE THREAD

**Issue by rschaub-epicor** [polygon-io/client-python#364]
When calling the get_ticker_details method on some tickers, some of the usual key value pairs in the results dictionary are missing (like 'market_cap'):

![image](https://user-images.githubusercontent.com/108374119/213325562-290dee3a-dbef-4010-9ad9-fc7a78914a96.png)

![image](https://user-images.githubusercontent.com/108374119/213325769-2ea978a2-9701-4d5e-89e5-e4fec2221045.png)

**Comment by antdjohns** [comment]
Hey @rschaub-epicor `get_ticker_details is not scriptable, you can access the returned objects properties using dot notation.

we will make note, it would be nice to access properties by bracketing strings.

**Comment by antdjohns** [comment]
Got it, makes sense. 

If we are not able to determine market cap, the field will be omitted. That said, we should be able to determine market cap, when requested; in most cases.

I will investigate more, thank you for bringing this up!

Are you able to provide some ticker examples?
How often are you running into this issue?

**Comment by justinpolygon** [comment]
Hey @rschaub-epicor, I'm going to close this issues since it doesn't look like there are any actions needed. I did check on this and it looks like we run our process each night to capture any recent filings. So, that might have been the delay in data population that you noticed.
