### ISSUE TITLE
Missing ticker root and ticker suffix fields in get_ticker_details response

### ISSUE THREAD

**Issue by Stormy110** [polygon-io/client-python#370]
**Describe the bug**
When querying the get_ticker_details function for a ticker with a "ticker_suffix", there is no ticker_suffix fields returned in the normal response unless you set raw=True.

**To Reproduce**
details = client.get_ticker_details(ticker="AVACU")

returns - 
TickerDetails(active=True, address=CompanyAddress(address1='2 EMBARCADERO CENTER,', address2='FLOOR 8', city='SAN FRANCISCO', state='CA', country=None, postal_code='94111'), branding=Branding(icon_url=None, logo_url='https://api.polygon.io/v1/reference/company-branding/d3d3LmF2YWxvbnNwYWMuY29t/images/2023-01-01_logo.png', accent_color=None, light_color=None, dark_color=None), cik='0001836478', composite_figi='BBG00ZGYP725', currency_name='usd', currency_symbol=None, base_currency_name=None, base_currency_symbol=None, delisted_utc=None, description='Avalon Acquisition Inc is a blank check company.', ticker_root='AVAC', homepage_url='https://www.avalonspac.com', list_date='2021-10-06', locale='us', market='stocks', market_cap=None, name='Avalon Acquisition Inc. Units', phone_number='415-423-0010', primary_exchange='XNAS', share_class_figi='BBG00ZGYP7X1', share_class_shares_outstanding=None, sic_code='6770', sic_description='BLANK CHECKS', ticker='AVACU', total_employees=4, type='UNIT', weighted_shares_outstanding=None)

A normal request through the docs returns the following - 
{'request_id': 'e9da60fa157ade88aaa6f010c76c6f57', 'results': {'ticker': 'AVACU', 'name': 'Avalon Acquisition Inc. Units', 'market': 'stocks', 'locale': 'us', 'primary_exchange': 'XNAS', 'type': 'UNIT', 'active': True, 'currency_name': 'usd', 'cik': '0001836478', 'composite_figi': 'BBG00ZGYP725', 'share_class_figi': 'BBG00ZGYP7X1', 'phone_number': '415-423-0010', 'address': {'address1': '2 EMBARCADERO CENTER,', 'address2': 'FLOOR 8', 'city': 'SAN FRANCISCO', 'state': 'CA', 'postal_code': '94111'}, 'description': 'Avalon Acquisition Inc is a blank check company.', 'sic_code': '6770', 'sic_description': 'BLANK CHECKS', '**ticker_root': 'AVAC', 'ticker_suffix': 'U',** 'homepage_url': 'https://www.avalonspac.com', 'total_employees': 4, 'list_date': '2021-10-06', 'branding': {'logo_url': 'https://api.polygon.io/v1/reference/company-branding/d3d3LmF2YWxvbnNwYWMuY29t/images/2023-01-01_logo.png'}, 'round_lot': 100}, 'status': 'OK'}

**Expected behavior**
Same result and fields as the raw docs results.

**Screenshots**

**Additional context**
https://api.polygon.io/v3/reference/tickers/AVACU?apiKey=***

**Comment by antdjohns** [comment]
Hey @Stormy110 thank you for bringing this to our attention. We have submitted a PR to get this patched.

**Comment by antdjohns** [comment]
Fixed:
pip install polygon-api-client --upgrade
```golang
TickerDetails(active=True,
address=CompanyAddress(address1='2 EMBARCADERO CENTER,', address2='FLOOR 8', city='SAN FRANCISCO', state='CA', country=None, postal_code='94111'),
branding=Branding(icon_url=None, logo_url='https://api.polygon.io/v1/reference/company-branding/d3d3LmF2YWxvbnNwYWMuY29t/images/2023-01-01_logo.png', accent_color=None, light_color=None, dark_color=None), 
cik='0001836478', 
composite_figi='BBG00ZGYP725', 
currency_name='usd', 
currency_symbol=None, 
base_currency_name=None,
base_currency_symbol=None, 
delisted_utc=None, 
description='Avalon Acquisition Inc is a blank check company.',
ticker_root='AVAC', 
ticker_suffix='U', 
homepage_url='https://www.avalonspac.com',
list_date='2021-10-06', 
locale='us', 
market='stocks', 
market_cap=None, 
name='Avalon Acquisition Inc. Units', 
phone_number='415-423-0010', 
primary_exchange='XNAS', 
share_class_figi='BBG00ZGYP7X1', 
share_class_shares_outstanding=None, 
sic_code='6770', 
sic_description='BLANK CHECKS', 
ticker='AVACU', 
total_employees=4, 
type='UNIT', 
weighted_shares_outstanding=None)
```
