### ISSUE TITLE
Hello, when trying to run simple.py,  I'm encountering the same `no module named polygon` issue noted (and closed out) some time ago, even after running `python3 -m pip install polygon-api-client` as suggested then.

### ISSUE THREAD

**Issue by HAuslander** [polygon-io/client-python#372]
Hello, when trying to run simple.py,  I'm encountering the same `no module named polygon` issue described in the referenced issue (even after running `python3 -m pip install polygon-api-client` as suggested).

I can, however alter the file by adding the line `import polygon` at the beginning, and then `import WebSocketClient` seems to work (though I realize that is not the optimal solution).

Moreover, the subsequent line in simple.py (i.e., `from polygon.websocket.models import WebSocketMessage`) still fails, and generates the following error message:

**ModuleNotFoundError: No module named 'polygon.websocket.models'**

Indeed, there is no sign of 'models' when  I run `dir(polygon.websocket)`, and instead, all I see is the following:

['CRYPTO_CLUSTER',
 'FOREX_CLUSTER',
 'STOCKS_CLUSTER',
 'WebSocketClient',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 'websocket_client']

_Originally posted by @HAuslander in https://github.com/polygon-io/client-python/issues/46#issuecomment-1414549571_

**Comment by antdjohns** [comment]
@HAuslander Sorry to hear that you're having issues. I tried to re-create the issue and failed. I am having no import issues.
In the README.md, we do recommend installing via pip 
```bash 
pip install polygon-api-client
```
I'm not certain, but there is a chance that your IDE is using a different interpreter than expected, or possibly different python installs on you system.
Here's an article I found on pip which may be helpful. https://realpython.com/what-is-pip/

I will leave this ticket open. Please let me know if you make any progress. Im running on a M1 Mac and using the Pycharm IDE.

**Comment by HAuslander** [comment]
I think perhaps my python3.7 was causing the problem (or I just needed an overhaul or fresh start with regards to python). Once I reinstalled Anaconda (which currently includes python3.9) I was able to run that part of the code.
