### ISSUE TITLE
get_ticker_types is failing for all AssetClass enum values other than STOCKS

### ISSUE THREAD

**Issue by magi-1** [polygon-io/client-python#374]
**Describe the bug**

I have the following subscriptions:

Basic: Currencies & Options
Starter: Stocks

Despite this, I seem to only be able to pull reference data for stock tickers and not the others. I see that reference data comes with the basic subscriptions and in the rest api documentation, all of the AssetClass enum values are valid search parameters. 

**To Reproduce**

```python
from polygon import RESTClient
from polygon.rest.models.common import AssetClass

client = RESTClient(api_key=polygon_key)
for kind in AssetClass.__members__.values():
    try:
        raw = client.get_ticker_types(asset_class=kind.value)
    except Exception as e:
        print(f"Failed for {kind} -> {e}")
```

Output:
```
Failed for AssetClass.OPTIONS -> polygon.rest.models.tickers.TickerTypes() argument after ** must be a mapping, not NoneType
Failed for AssetClass.CRYPTO -> polygon.rest.models.tickers.TickerTypes() argument after ** must be a mapping, not NoneType
Failed for AssetClass.FX -> polygon.rest.models.tickers.TickerTypes() argument after ** must be a mapping, not NoneType
```

Full traceback:

```python
Cell In[15], line 10
      7 client = RESTClient(api_key=polygon_key)
      8 for kind in AssetClass.__members__.values():
---> 10     raw = client.get_ticker_types(asset_class=kind.value)

File .../python3.11/site-packages/polygon/rest/reference.py:240, in TickersClient.get_ticker_types(self, asset_class, locale, params, raw, options)
    229 """
    230 List all ticker types that Polygon.io has.
    231 
   (...)
    236 :return: Ticker Types.
    237 """
    238 url = "/v3/reference/tickers/types"
--> 240 return self._get(
    241     path=url,
    242     params=self._get_params(self.get_ticker_types, locals()),
    243     deserializer=TickerTypes.from_dict,
    244     raw=raw,
    245     result_key="results",
    246     options=options,
    247 )

File .../python3.11/site-packages/polygon/rest/base.py:108, in BaseClient._get(self, path, params, result_key, deserializer, raw, options)
    106         obj = [deserializer(o) for o in obj]
    107     else:
--> 108         obj = deserializer(obj)
    110 return obj

File .../python3.11/site-packages/polygon/rest/models/tickers.py:189, in TickerTypes.from_dict(d)
    187 @staticmethod
    188 def from_dict(d):
--> 189     return TickerTypes(**d)

TypeError: polygon.rest.models.tickers.TickerTypes() argument after ** must be a mapping, not NoneType
```

Clearly as evidenced by `obj = [deserializer(o) for o in obj]`, it contains Nonetypes which are causing the unpacking to fail here `TickerTypes(**d)`. Guess my issue boils down to why I am getting empty responses.

**Expected behavior**

I should be able to query ticker types for all asset classes.

**Comment by magi-1** [comment]
Okay, so running the query on the REST api docs works, and I just a response object like:

request: `https://api.polygon.io/v3/reference/tickers/types?asset_class=fx&locale=global`

```json
{
    "results": null,
    "count": 0,
    "status": "OK",
}
```

So either there is something wrong with the api or the information on the [pricing page](https://polygon.io/pricing) is incorrect and the reference data bullet point for all asset classes needs to be moved out of the "Basic" / free subscription and into just the paid versions.

**Comment by justinpolygon** [comment]
Hi @magi-1 , first off thanks for checking out Polygon.io and playing around with the Python client library. What type of historical data are you trying to pull down? I might be able to help out here.

**Comment by justinpolygon** [comment]
Hey @magi-1, wanted to follow up here. You're getting the error in python because there are zero results returned for options, cyrpto, and fx from the Ticker Types API. This happens on the web API too if you test it. There is only data for stocks from with API. I suspect you might be looking for the Tickers API but let me know. What type of data were you looking for here or did you already solve the issue?

**Comment by justinpolygon** [comment]
Hey, I'm going to close this. Please comment/re-open if you still need help here. Thank you.
