### ISSUE TITLE
no wrapper for option quotes

### ISSUE THREAD

**Issue by agcap1** [polygon-io/client-python#376]
**Is your feature request related to a problem? Please describe.**
frustrating to request option quote

**Describe the solution you'd like**
the client library is incomplete, its very difficult for new programmers to work with this

**Describe alternatives you've considered**

**Additional context**

**Comment by justinpolygon** [comment]
Thanks for the feedback @agcap1. We're working on example code snippets that should really help here. I'll leave this issue open and circle back when we commit them. Were you able to solve the problem or you need some help here still?

**Comment by agcap1** [comment]
Thanks for the reply. I actually had to switch brokerages so my testing has
been paused while the transfer takes place. However, I think i found a way
to work around the variation in price, but will definitely collect my own
meta data of real time quote comparison to share with you. This way ill be
able to identify if the problem is from lag within my program or if there
is lag from opra to you.
Ill let yall know when/if i end up building a large collection of evidence.
Or if i solve the issue completely on my end.

**Comment by justinpolygon** [comment]
Just wanted to follow up here. We've have added 22 options example code snippets via PR https://github.com/polygon-io/client-python/pull/390 into the `/examples` directory in this repo. There some rest and websocket examples. So, hopefully that will get things started quickly when you pick it back up.
