### ISSUE TITLE
Limit in method 'get_macd'

### ISSUE THREAD

**Issue by avryzhov** [polygon-io/client-python#378]
**Describe the bug**

When I launch my code, I get error with describe TypeError: get_macd() got an unexpected keyword argument 'limit'

        bars = client.get_macd(
ticker="BABA", timespan='day', short_window=9, signal_window=12, long_window=26, timestamp = '2023-02-01',
        series_type='close', limit=200)
bars2=bars.values

df = pd.DataFrame(bars2)
#df.index = pd.DatetimeIndex( pd.to_datetime(df['timestamp']/1000,unit='s').dt.date )
df.index = pd.DatetimeIndex( pd.to_datetime(df['timestamp']/1000,unit='s') ) 
df.index.name = 'Date'
df

**To Reproduce**
I also didn't see argument 'limit' here:
a=client.get_macd
inspect.signature(a)

<Signature (ticker: str, timestamp: Union[str, int, datetime.datetime, datetime.date, NoneType] = None, timestamp_lt: Union[str, int, datetime.datetime, datetime.date, NoneType] = None, timestamp_lte: Union[str, int, datetime.datetime, datetime.date, NoneType] = None, timestamp_gt: Union[str, int, datetime.datetime, datetime.date, NoneType] = None, timestamp_gte: Union[str, int, datetime.datetime, datetime.date, NoneType] = None, timespan: Union[str, NoneType] = None, short_window: Union[int, NoneType] = None, long_window: Union[int, NoneType] = None, signal_window: Union[int, NoneType] = None, adjusted: Union[bool, NoneType] = None, expand_underlying: Union[bool, NoneType] = None, order: Union[str, polygon.rest.models.common.Order, NoneType] = None, params: Union[Dict[str, Any], NoneType] = None, series_type: Union[str, polygon.rest.models.common.SeriesType, NoneType] = None, raw: bool = False, options: Union[polygon.rest.models.request.RequestOptionBuilder, NoneType] = None) -> Union[polygon.rest.models.indicators.MACDIndicatorResults, urllib3.response.HTTPResponse]>

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by justinpolygon** [comment]
Hey @avryzhov, `get_macd` doesn't support `limit`. So, just drop that and it should work. You can see the [get_macd function here](https://github.com/polygon-io/client-python/blob/3cee0bce05a8f85cdfa4aaa6885123260dc3a7e3/polygon/rest/indicators.py#L177).

Here's a working code snippet:

```python
from polygon import RESTClient
import pandas 
client = RESTClient()

bars = client.get_macd(
    ticker="BABA", 
    timespan='day', 
    short_window=9, 
    signal_window=12, 
    long_window=26, 
    timestamp = '2023-02-01',
    series_type='close')

bars2=bars.values
df = pandas.DataFrame(bars2)
df.index = pandas.DatetimeIndex( pandas.to_datetime(df['timestamp']/1000,unit='s') )
df.index.name = 'Date'
print(df)
```
