### ISSUE TITLE
Request: Documentation

### ISSUE THREAD

**Issue by sandorvasas** [polygon-io/client-python#39]
Documentation of the python api specifically would be really useful.

I'm stuck with e.g. `reference_stock_financials()`, I'd like to set the period param, but the query params are just defined as `**query_params`, so I have no clue what how to specify them.

**Comment by levidehaan** [comment]
Documentation is very important. The lack of documentation is pretty unfortunate as it leaves the users of your API's sitting around trying to figure things out instead of getting right to using the data we pay for.
Thanks.

**Comment by jbonzo** [comment]
Thank you for the feedback. We have merged #42 which we hope better document this functionality.
