### ISSUE TITLE
Batch requests

### ISSUE THREAD

**Issue by yumikohey** [polygon-io/client-python#397]
**Is your feature request related to a problem? Please describe.**
If I want to fetch multiple strike price trades, do we support batching requests?

**Describe the solution you'd like**
If it's not yet available, I think batch requests will be great

**Describe alternatives you've considered**

**Additional context**

**Comment by justinpolygon** [comment]
Hey @yumikohey, the underlining API doesn't support batch requests but I'll raise that as a feature with the team. What I'd suggest as a good alternative is using a thread pool to make requests concurrently vs in parallel. You can get very large speed ups using this technique.

Here's an example:

```python
import requests
from concurrent.futures import ThreadPoolExecutor

# Function to connect to API
def connect_to_api(url):
    response = requests.get(url)
    return response

# Define a list of URLs to connect to
urls = ['https://api.example.com/endpoint1', 'https://api.example.com/endpoint2', 'https://api.example.com/endpoint3', 'https://api.example.com/endpoint4']

# Create a thread pool with 8 workers
with ThreadPoolExecutor(max_workers=8) as executor:
    # Submit each URL to the thread pool for processing
    futures = [executor.submit(connect_to_api, url) for url in urls]

    # Wait for all threads to finish and retrieve the results
    results = [f.result() for f in futures]

# Print the results
for result in results:
    print(result.json())
```

So, you could probably modify this code to whatever your use-case. You can also update the to a much large number depending on how many tickers you're trying to access.

**Comment by justinpolygon** [comment]
Hey, I'm going to close this for now since this is more of a backend API request. Thanks for the feedback. Hopefully the thread pool works for your use case.

**Comment by justinpolygon** [comment]
Another option here is to use the https://polygon.io/docs/stocks/get_v2_snapshot_locale_us_markets_stocks_tickers API and fetch all prices and just filter for the tickers you're interested in. If that doesn't work let me know and I'll update the feature request on my end. Cheers.
