### ISSUE TITLE
MinuteSnapshot missing 't' (timestamp), 'n' (transactions)

### ISSUE THREAD

**Issue by tlk3** [polygon-io/client-python#440]
Python library dataclass missing fields returned by the API. 

Updated version with newly added lines commented: **# added**

`
class MinuteSnapshot:
    "Most recent minute bar."
    accumulated_volume: Optional[float] = None
    open: Optional[float] = None
    high: Optional[float] = None
    low: Optional[float] = None
    close: Optional[float] = None
    volume: Optional[float] = None
    vwap: Optional[float] = None
    otc: Optional[bool] = None
    timestamp: Optional[int] = None        # added
    transactions: Optional[int] = None     # added

    @staticmethod
    def from_dict(d):
        return MinuteSnapshot(
            d.get("av", None),
            d.get("o", None),
            d.get("h", None),
            d.get("l", None),
            d.get("c", None),
            d.get("v", None),
            d.get("vw", None),
            d.get("otc", None),
            d.get("t", None),        # added
            d.get("n", None),       # added
        )
`

**Comment by justinpolygon** [comment]
Thanks for submitting this @tlk3. I'm checking this out now.

**Comment by justinpolygon** [comment]
Hey, v1.9 has the fix for this. Thanks for reporting.
