### ISSUE TITLE
No module named polygon

### ISSUE THREAD

**Issue by stoxllc** [polygon-io/client-python#46]
hello, everyone. newbie here.

i basically run the simple websocket demo and it gives me the error ModuleNotFoundError: No module named 'polygon'.

This I believe is line 4 in the code : 

from polygon import WebSocketClient, STOCKS_CLUSTER

I have installed the polygon-api-client (pip install polygon-api-client), so I'm not sure what am I missing.

Thanks in advance.

**Comment by joshterrill** [comment]
Make sure that the pip you're using is mapped to the same version of python that you're running. I.e. if you have multiple versions of python installed, such as python 2 and 3, you may need to run pip3 install instead of pip, and vice versa.

**Comment by ClarenceChen96** [comment]
I'm sure that my pip is mapped to my version of python correctly, but I have the same issue. After running pip install polygon-api-client, I still get the same "no module named polygon" error. 


Here are some results
![image](https://user-images.githubusercontent.com/55094295/108144377-86456700-7097-11eb-8283-cb023708a436.png)

**Comment by ClemFournier** [comment]
I ran into the same issue, made it work by calling **pip install** with the python version I wanted to install the package for: 

**python3 -m pip install polygon-api-client**

**Comment by matichenor** [comment]
Looks like this was a python versioning issue.  Ping us if we can help with anything else!

**Comment by HAuslander** [comment]
Hello, when trying to run simple.py,  I'm encountering the same `no module named polygon` issue described above (even after running `python3 -m pip install polygon-api-client` as suggested).

I can, however alter the file by adding the line `import polygon` at the beginning, and then `import WebSocketClient` seems to work (though I realize that is not the optimal solution).

Moreover, the subsequent line in simple.py (i.e., `from polygon.websocket.models import WebSocketMessage`) still fails, and generates the following error message:

**ModuleNotFoundError: No module named 'polygon.websocket.models'**

Indeed, there is no sign of 'models' when  I run `dir(polygon.websocket)`, and instead, all I see is the following:

['CRYPTO_CLUSTER',
 'FOREX_CLUSTER',
 'STOCKS_CLUSTER',
 'WebSocketClient',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 'websocket_client']
