### ISSUE TITLE
_paginate_iter throws `KeyError`

### ISSUE THREAD

**Issue by oboxer** [polygon-io/client-python#467]
**Describe the bug**

[_paginate_iter](https://github.com/polygon-io/client-python/blob/master/polygon/rest/base.py#L201) throws `KeyError: 'results'` when `results` doesn't exist in `resp`

**To Reproduce**

Call `list_aggs` with `"/v2/aggs/ticker/O:SPY230703C00408000/range/5/minute/2023-07-03/2023-07-04"`

**Expected behavior**

IMHO, this is not an error. When there's no `results` in `resp`, just skip it, don't throw a key error.
Change `for t in decoded[result_key]:` to `for t in decoded.get(result_key, []):` should be enough

**Screenshots**

N/A

**Additional context**

N/A

**Comment by justinpolygon** [comment]
Hey, thanks for submitting this @oboxer. I'll check it out.

**Comment by justinpolygon** [comment]
We have released v1.12.0 that fixes this issue and returns and empty array when no results are found.

Please see https://github.com/polygon-io/client-python/releases/tag/v1.12.0

Thanks again for reporting this and helping up improve the library.
