### ISSUE TITLE
list_universal_snapshots() does not properly support the "options" market_type

### ISSUE THREAD

**Issue by buege** [polygon-io/client-python#476]
**Describe the bug**
`list_universal_snapshots()` takes either a `str` or a `SnapshotMarketType` as the market_type argument.  However, `polygon.rest.models.SnapshotMarketType` does not include a market_type enumeration for options, however the UniversalSnapshot REST API does accept `"options"` as a value for the parameter `type`.  Furthermore, when attempting to pass the string "options" as the market_type parameter, the string is not properly converted from  the `market_type` parameter to the `type` parameter required by the UniversalSnapshot API (the invalid parameter `market_type` is used in the GET request).  This results in the function returning a listing of snapshots for stocks instead (which is the default response from the UniversalSnapshot API).

**To Reproduce**
`list_universal_snapshots(market_type="options", raw=True)` returns universal snapshots for stocks (same results as when market_type is None).

**Expected behavior**
`list_universal_snapshots(market_type="options", raw=True)` should return the same results as
GET https://api.polygon.io/v3/snapshot?type=options&apiKey=<my_key> which does return valid option snapshots.

**Comment by justinpolygon** [comment]
Thank you for reporting this. I have confirmed the bug and am working on a patch.

**Comment by justinpolygon** [comment]
This has been fixed in the latest release v1.12.1. Thanks again for reporting this and helping us get it fixed.
