### ISSUE TITLE
Support MinuteSnapshot in UniversalSnapshot

### ISSUE THREAD

**Issue by parthnagarkar** [polygon-io/client-python#481]
**Describe the solution you'd like**
I would like to access MinuteSnapshot data in the new UniversalSnapshot. 

**Describe alternatives you've considered**
Right now, it is supported in v2/snapshot, but it looks like v2/snapshot is already deprecated.

**Comment by nithesh10** [comment]
yeah i need it too

**Comment by justinpolygon** [comment]
Hi @parthnagarkar and @nithesh10, thanks for commenting here. This is more of a feature request for the underlining API to support MinuteSnapshot within UniversalSnapshots. I've passed this request over to the product and support teams internally so they can track it. I don't have an ETA for if/when this will happen though. Do you mind emailing me justin@polygon.io and I'll pass along your info so they know who's asking and that's tracked too. Thank you.
