### ISSUE TITLE
BaseClient.decode() throws an exception when /v3/reference/dividends returns an empty page

### ISSUE THREAD

**Issue by bfoz** [polygon-io/client-python#499]
Using v1.12.3 to fetch all dividends for a given date, I get an exception for what I suspect is the final page of results:

```
...
  File "/Users/bfoz/.local/share/virtualenvs/project04-bNStgEKY/lib/python3.11/site-packages/polygon/rest/base.py", line 196, in _paginate_iter
    decoded = self._decode(resp)
              ^^^^^^^^^^^^^^^^^^
  File "/Users/bfoz/.local/share/virtualenvs/project04-bNStgEKY/lib/python3.11/site-packages/polygon/rest/base.py", line 70, in _decode
    return self.json.loads(resp.data.decode("utf-8"))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bfoz/.asdf/installs/python/3.11.0/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bfoz/.asdf/installs/python/3.11.0/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bfoz/.asdf/installs/python/3.11.0/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

Trapping the exception at [base.py line 196](https://github.com/polygon-io/client-python/blob/e77c22b1479979841e47eda52fd3a01f06f7200c/polygon/rest/base.py#L196), and inspecting the response object...

```
            try:
                decoded = self._decode(resp)
            except:
                breakpoint()
```

```
> /Users/bfoz/.local/share/virtualenvs/project04-bNStgEKY/lib/python3.11/site-packages/polygon/rest/base.py(200)_paginate_iter()
-> if result_key not in decoded:
(Pdb) resp.status
200
(Pdb) resp.data
b''
```

It appears that the server returned an empty response body, and [json.loads()](https://github.com/polygon-io/client-python/blob/e77c22b1479979841e47eda52fd3a01f06f7200c/polygon/rest/base.py#L69) couldn't handle it.

I'm not sure if paginated results are allowed to have empty pages or if this is a server problem. Either way, it seems like it might be a good idea for the client to guard against this case if the json parser is going to be so picky.

**Comment by justinpolygon** [comment]
Hey @bfoz, do you happen to have the query that created that? I'm trying to reproduce on my end. I keep getting and empty array when trying things that don't return results.

**Comment by bfoz** [comment]
I'm using `polygon.RESTClient(key).list_dividends(None, limit=1000)` which seems to translate to `https://api.polygon.io/v3/reference/dividends?limit=1000`. 

The call that actually fails appears to be the 6th request. 

I just tried it again and the URL that failed was `https://api.polygon.io/v3/reference/dividends?cursor=YXA9MjAyMy0wNi0yNyZhcz1JRlYmbGltaXQ9MTAwMCZvcmRlcj1kZXNjJnNvcnQ9ZXhfZGl2aWRlbmRfZGF0ZQ`. I suspect that cursor doesn't mean much anymore, but there it is.

**Comment by justinpolygon** [comment]
Great, thanks. I have a patch here that should fix it https://github.com/polygon-io/client-python/pull/500. Just wanted to do some testing. A useful tip, is that you can use `RESTClient(key, trace=True)` and it will dump the url and headers so that you can see what's happening behind the scenes. I'll test things on my end and likely do a release shortly. Thanks for reporting this.

**Comment by justinpolygon** [comment]
Hey @bfoz, we have applied a fix to the backend API to correct this issue as well. Do you mind retesting to verify this is fixed. Thanks again for reporting this since it really helps improve the platform for everyone.

**Comment by bfoz** [comment]
The script that I was testing with (about the same, but with a date) magically started working again! 

Your test code eventually finished with `365978` results.

It looks like you fixed it. Thanks!

**Comment by justinpolygon** [comment]
Perfect, thank you for following up.
