### ISSUE TITLE
StocksEquitiesAggregatesApiResponse is not JSON serializable

### ISSUE THREAD

**Issue by xplusplus** [polygon-io/client-python#50]
I'm attempting to serialize the response from the `stocks_equities_aggregates()` function in the Python API and I run into an error stating that the response object `StocksEquitiesAggregatesApiResponse` is not JSON serializable:

![image](https://user-images.githubusercontent.com/3989613/107139786-ad02e100-68d2-11eb-9eca-6b583368ec20.png)

**Comment by matichenor** [comment]
We have a new version of the library which enables this.  You can get the raw urrllib3 response and parse the response text into json.  

See the [Getting Started](https://polygon-api-client.readthedocs.io/en/latest/Getting-Started.html) section in our docs or view the [examples](https://github.com/polygon-io/client-python/blob/master/examples) directory.
