### ISSUE TITLE
**kwargs never passed on to handle_msg callback

### ISSUE THREAD

**Issue by androslee** [polygon-io/client-python#504]
https://github.com/polygon-io/client-python/blame/0aa413cb800121d7f38d52d215197451d3e0a800/polygon/websocket/__init__.py#L178

this never passes any custom **kwargs you specify to the "handle_msg" callback.  you can set them in the constructor for this "WebSocketClient" object, but then they can never be used by the "handle_msg" callback function.

other than making something global, i'm not sure how to share something between the callback and other functions within the module.

**Comment by androslee** [comment]
i was modifying one of the examples i already saw:

- stocks-ws_extra.py (but using the options endpoint since that's what my API subscription allows)

but then i wanted to take that example, and turn it into a callable module that something else could call, have "this" run for maybe 1 hour, then return all the data it gathered.


for my use, what i would really like to have running is:

`
def handle_message_andros(msgs: List[WebSocketMessage])

  for m in msgs:
    shared_input_queue.put(m)


def top_function_andros(shared_input_queue):
  # do things with the data in the queue
  return

def run_function_periodically(shared_input_queue):
    while True:
        top_function_andros(shared_input_queue)
        time.sleep(60)
`

i would like the "stocks-ws_extra.py" 2 threaded example, to be able to be called from another module, and whatever data "handle_msg" gets, to be able to be stored into a threadsafe queue, that something like "top_function_andros" could access, from within it's module.

**Comment by justinpolygon** [comment]
Got it. This makes sense. You want to subscribe to the feed and then run tasks based off what you see. Sure, here's some example code that likely does what you want. This code sets up a real-time event stream websocket client to listen for market Agg updates on options. At its core, the code is divided into two main classes: MessageHandler and MyClient.

MessageHandler Class:

- This class is responsible for processing incoming messages from the WebSocket client.
- It maintains an asynchronous queue (handler_queue) to hold the messages temporarily.
- The add method puts the incoming messages into this queue, effectively acting as a producer.
- The start_handling method continuously polls messages from this queue and processes them. It creates asynchronous tasks to handle each message, ensuring concurrent processing of multiple messages.
- For handling the actual message, it delegates to the handle_response method, which simply prints the message to the console.

MyClient Class:

- This is the main orchestrator of the entire flow.
- Upon initialization, it sets up the WebSocket client with specific configurations, like the feed type (RealTime), market type (Options), and a pattern for the subscriptions.
- The start_event_stream method does the heavy lifting. It concurrently establishes a connection to the WebSocket client and starts the message handling loop from the MessageHandler class.
- The script's entry point, the main function, initializes the MyClient class and begins the event stream. When executed, the program will establish a connection to the Polygon.io WebSocket, listen for market updates on options, and print those messages in real-time. But, this is done via a queue so it doesn't block messages something though

```python
import asyncio
from typing import Optional, Union
from polygon import WebSocketClient
from polygon.websocket.models import Market, Feed

class MessageHandler:
    def __init__(self):
        self.handler_queue = asyncio.Queue()

    async def add(self, message_response: Optional[Union[str, bytes]]) -> None:
        await self.handler_queue.put(message_response)  # producer

    async def start_handling(self) -> None:
        handler_tasks: List[asyncio.Task] = []
        while True:
            message_response = await self.handler_queue.get()
            task = asyncio.create_task(self.handle_response(message_response))
            handler_tasks.append(task)

            # Clean up finished tasks
            handler_tasks = [t for t in handler_tasks if not t.done()]
        await asyncio.gather(*handler_tasks)

    async def handle_response(self, message_response: Optional[Union[str, bytes]]) -> None:
        print(message_response)
        # add your code here

class MyClient:
    def __init__(self, feed, market, polygon_websocket_client=None):
        self.polygon_websocket_client = polygon_websocket_client or WebSocketClient(
            api_key="XXXX",
            feed=feed,
            market=market,
            subscriptions=["A.*"],
        )
        self.message_handler = MessageHandler()

    async def start_event_stream(self):
        await asyncio.gather(
            self.polygon_websocket_client.connect(self.message_handler.add),
            self.message_handler.start_handling()
        )


async def main():
    my_client = MyClient(
            feed=Feed.RealTime,
            market=Market.Options,
    )
    await asyncio.gather(my_client.start_event_stream())

asyncio.run(main())
```

Hope this example code helps. I'll add it to the repo for anyone else that's looking.

**Comment by androslee** [comment]
this looks wonderful.  i will shuffle things around as my usage right here wasn't using asyncio yet, but this does sound like what i was hoping for.  thank you for taking the time and coming up with this additional example.  

and folks, remember to adjust "Feed.Delayed" to the value for the API level you are paying for (for any people from google seeing this later that don't know it yet).

**Comment by justinpolygon** [comment]
Perfect, happy that helped! Great point around `Feed.Delayed`. Will do.

Cheers

**Comment by androslee** [comment]
this might be outside the scope of polygon/your API, but since your websocket only gets responses/live data during trading hours, do you have any recommendations of how i might be able to test/verify the websocket client/code when it's outside of live market hours?

it might be a big ask, and i have no idea what your infrastructure is like, but what if the websocket client had an optional debug flag:

WebSocketClient(
            api_key="XXXX",
            feed=feed,
            market=market,
            subscriptions=["A.*"],
            debug=True
        )

(and so yes, the URL endpoint and backend would have to support this also)


this still sends you to the same API entry point INTO polygon.  HOWEVER, the backend subscribes you to a different datafeed as the response.  as i suspect you are not customizing the payload for much of any individual user, this "debug" response payload would be very simple.  it would:

- be given every 60 seconds (match the same rate as the production datafeed)
- data would maybe just "t":31216198 , the current millisecond unix timestamp or something.  maybe also "debug": True, so it's very obvious when we look at the whole payload "oh right, that's what i'm doing"

{
  "t":1659456114000,
  "debut":True
}

that way, we could still manage to do some websocket callback debugging after market hours

**Comment by justinpolygon** [comment]
Hey @androslee, we don't support anything like this right now. You'll only get websocket activity for options when the market is open. However, I really like this idea and it's an interesting suggestion. I'll pass this along to the team. The crypto APIs are open 24/7 so you might be able to do some logic testing there but I know what you mean re: only being able to test stocks/options/indices/etc when the market are open.

**Comment by androslee** [comment]
i mean, i like that idea, but, i'd have to be paying for access to the crypto API endpoint, right?  i don't think i see anything about websocket on any free tier.

otherwise, i don't mind getting a crypto data payload ANYTIME as long as it could prove my callback is working.  that's better than the "nothing" i can do after hours right now.
