### ISSUE TITLE
Does company fundamental data go back any further?

### ISSUE THREAD

**Issue by JeremyWhittaker** [polygon-io/client-python#522]
I'm pulling company financial data with this line of code:
`for t in client.vx.list_stock_financials(ticker=stock_ticker, filing_date_gte=filing_date_gte):

I'm specifying filing_date_gte with a year value of 2000 but the API stops after 2009. The symbol is 'AAPL' so I assume it would go back a lot further. Is there a way to retrieve older financial reports?

**Comment by justinpolygon** [comment]
Hi @JeremyWhittaker, I checked using the API itself via the docs https://polygon.io/docs/stocks/get_vx_reference_financials and I'm only seeing data back to 2009 as well. I'll check with the team to see how far back historical data goes then get back to you.

**Comment by justinpolygon** [comment]
Hi @JeremyWhittaker, I checked with the team and the dataset start in 2009.

**Comment by JeremyWhittaker** [comment]
> Hi @JeremyWhittaker, I checked with the team and the dataset start in 2009.

Thank you. Is there any way to access archived data prior to 2009? I'm trying to analyze the 2008 financial crisis in my code and how certain fundamentals performed.

**Comment by justinpolygon** [comment]
Sorry, 2009 is the earliest data we have. We don't have anything for 2008. [This article](https://www.dwt.com/insights/2009/02/sec-adopts-final-rules-on-xbrl-mandates-use-of-int) has more details on the phase-in period the SEC implemented when it started requiring XBRL in financial reports (we only pull data from XBRL financial reports which started in 2009. So, this is the reason the data set starts in 2009 and nothing farther back.

**Comment by JeremyWhittaker** [comment]
Got it, thanks! Appreciate your quick response!
