### ISSUE TITLE
host should be parameter when init WebsocketClient class.

### ISSUE THREAD

**Issue by Achilles718611** [polygon-io/client-python#53]
For production keys, websocket url is polyfeed.polygon.io not socket.polygon.io.
So host should be parameterized.

**Comment by matichenor** [comment]
Also raised and upvoted in https://github.com/polygon-io/client-python/issues/58 :

```
It doesn't appear that this value is configurable:

[client-python/polygon/websocket/websocket_client.py](https://github.com/polygon-io/client-python/blob/ec93d27df053270f8ac01b9871ecf842242c9567/polygon/websocket/websocket_client.py#L13)

Line 13 in [ec93d27](https://github.com/polygon-io/client-python/commit/ec93d27df053270f8ac01b9871ecf842242c9567)

 DEFAULT_HOST = "socket.polygon.io" 
Am I missing something? Is there an option for using something other than DEFAULT_HOST? I would like to use the delayed vs. the socket websocket endpoint as I am still in earlier evaluation stages with this product.
```

**Comment by matichenor** [comment]
This feature is now availble in the latest python library! 

See: https://polygon-api-client.readthedocs.io/en/latest/WebSocket-Enums.html#polygon.websocket.models.Feed

For more, check out the [Getting Started](https://polygon-api-client.readthedocs.io/en/latest/Getting-Started.html) section in our docs or view the [examples](https://github.com/polygon-io/client-python/blob/master/examples) directory.
