### ISSUE TITLE
get_grouped_daily_aggs should return Crypto tickers as well

### ISSUE THREAD

**Issue by evanvolgas** [polygon-io/client-python#540]
**Is your feature request related to a problem? Please describe.**

Crypto ticker data currently shows up in the `/v2/aggs/ticker/{stocksTicker}/range/{multiplier}/{timespan}/{from}/{to}` endpoint but not in the `/v2/aggs/grouped/locale/us/market/stocks/{date}` endpoint. This in turn means that `get_grouped_daily_aggs` fails to show any data for crypto tickers. This is inconsistent with the `list_aggs` endpoint, which does allow you to query for crypto tickers. 

**Describe the solution you'd like**
I believe that crypto ticker data should be included in `get_grouped_daily_aggs`

**Describe alternatives you've considered**
You could technically crawl `all_tickers` for a list of crypto tickers (ones prefixed with "X:" if I'm not mistaken) and then pass those to `list_aggs`. I'll probably end up doing this as a workaround, although I use `get_grouped_daily_aggs` elsewhere in my codebase.

**Additional context**
It just seems inconsistent to me that `get_grouped_daily_aggs` doesn't include crypto data but `list_aggs` does. It's possible to work around it, but it would be a nice feature if I didn't have to.

**Comment by justinpolygon** [comment]
Hi @evanvolgas, you can use the grouped crypto api for that. Here's the docs:

https://polygon.io/docs/crypto/get_v2_aggs_grouped_locale_global_market_crypto__date

Here's an example:

https://github.com/polygon-io/client-python/blob/master/examples/rest/crypto-grouped_daily_bars.py

Cheers

**Comment by evanvolgas** [comment]
Sorry for not picking up on that in the documentation. This works exactly like the example. Thanks for clarifying and sorry again for misunderstanding.

**Comment by justinpolygon** [comment]
No worries all good. Just happy it solved the problem. Cheers.
