### ISSUE TITLE
Python 3 native async methods

### ISSUE THREAD

**Issue by HarryR** [polygon-io/client-python#56]
asyncio primitives are becoming more prevalent with Python 3, the `await` keyword for example has an infectious nature.

The current Python swagger API doesn't support async, it would be good to support async in addition to Python 2.x compatible code.

[aiohttp](https://docs.aiohttp.org/en/stable/) offers an interface similar to `requests`.

What are your thoughts? If the API code is generated, can you suggest somewhere that asyncio could be implemented upstream to benefit your project?

**Comment by yehoshuadimarsky** [comment]
+1 I'd love this. Seems all we have to do is replace these `requests` parts with `aiohttp` and just make it all async/await, no? I'd be happy to whip up a quick PR for this, unless I'm missing something more fundamental?

https://github.com/polygon-io/client-python/blob/1509ddd88af22f3133f7855dc9f8007fb486b4f7/polygon/rest/client.py#L30-L35

**Comment by morningvera** [comment]
Closing this stale issue because we're currently not planning to implement it. We suggest writing a lightweight async wrapper around the client if needed.
