### ISSUE TITLE
Visual Studio cant find RESTClient but I figured it out

### ISSUE THREAD

**Issue by pythyon** [polygon-io/client-python#57]
The sample would not run throwing an error on the first line with:

from polygon import RESTClient

which caused quite a lot of searching until I figured out that even with installing the client that that reference is 2 folders down the script's tree and in its own __init__ file. Aparently VSS is stricter about references.

The fix to get the sample to work is to change that first line to:

from polygon.rest.client  import RESTClient

Just hope that this helps someone else having difficulty getting to first base =;?)

**Comment by matichenor** [comment]
Thanks for posting the fix.  We'll see if we can improve our doc going forward.

**Comment by MotorCityCobra** [comment]
Still not fixed. I don't know how to import RESTClient after the pip install.

**Comment by justinpolygon** [comment]
Hey @MotorCityCobra, can you be a bit more specific about what you're seeing maybe a screenshot or error message. We have lots of example code here that you should be able to run. You'll just need to add in your API key either right in the script of as an environment variable, although I don't know how to do that in Visual Studio.

See: https://github.com/polygon-io/client-python/tree/master/examples/rest

**Comment by justinpolygon** [comment]
Hey @MotorCityCobra, what API are you hitting and what date ranges are you looking for? It's likely that you're just missing a limit param or something. I can likely help you write a script if you provide me the API and date ranges. Can you post your script too?

**Comment by MotorCityCobra** [comment]
client = RESTClient(api_key="<my_API_KEY")

ticker = "SPY"

# List Aggregates (Bars)
bars = client.get_aggs(ticker=ticker, multiplier=1, timespan="minute", from_="2020-01-09", to="2023-06-08")

# 
client = RESTClient(api_key="pJw_4Dg2jUn6wqMSaYpsHaSsLKjHyOBu")
​
ticker = "SPY"
​
# List Aggregates (Bars)
bars = client.get_aggs(ticker=ticker, multiplier=1, timespan="minute", from_="2020-01-09", to="2023-06-08")
​
len(
len(bars)
5000


Yes, maybe this is not how it is done. I don't know. Should this be returning more than 5k prices? There are 390 minutes in a day, so this is not even 13 days?

**Comment by MotorCityCobra** [comment]
client = RESTClient(api_key="<my_API_KEY")

ticker = "SPY"

List Aggregates (Bars)
bars = client.get_aggs(ticker=ticker, multiplier=1, timespan="minute", from_="2020-01-09", to="2023-06-08")

​
len(
len(bars)
5000


Yes, maybe this is not how it is done. I don't know. Should this be returning more than 5k prices? There are 390 minutes in a day, so this is not even 13 days?

**Comment by justinpolygon** [comment]
Hey @MotorCityCobra, please try something like this:

```
from polygon import RESTClient
from datetime import datetime
from dateutil.relativedelta import relativedelta

# client = RESTClient("XXXXXX") # hardcoded api_key is used
client = RESTClient()  # POLYGON_API_KEY environment variable is used

# Define your ticker
ticker = "AAPL"

# Define your start and end years
start_year = 2020
end_year = 2022

# Initialize start date
start_date = datetime(start_year, 1, 1)

# Create an empty list to store all the aggs
all_aggs = []

while start_date.year <= end_year:
    # Calculate end date as the last day of the current month
    end_date = start_date + relativedelta(day=31)
    
    # Make sure we don't exceed today's date or the end_year
    end_date = min(end_date, datetime.now(), datetime(end_year, 12, 31))

    # Print status message
    print(f"Fetching data for {ticker} from {start_date.strftime('%Y-%m-%d')} to {end_date.strftime('%Y-%m-%d')}")

    aggs = client.get_aggs(
        ticker,
        1,
        "minute",
        start_date.strftime('%Y-%m-%d'),
        end_date.strftime('%Y-%m-%d'),
    )

    # Add the current month's aggs to the list
    all_aggs.append(aggs)

    # Increment start_date to the next month
    start_date += relativedelta(months=1)

# Print all the aggs at the end
for aggs in all_aggs:
    print(aggs)

```

**Comment by justinpolygon** [comment]
Hey @MotorCityCobra, hopefully that worked out. Here's a slightly refactored version that removed two end_dates and just uses one. Also, it looks like I was using all_aggs and grouping by day. You might just want one big list. So, here's a script with those two changes:

```
from polygon import RESTClient
from datetime import datetime
from dateutil.relativedelta import relativedelta

# client = RESTClient("XXXXXX") # hardcoded api_key is used
client = RESTClient()  # POLYGON_API_KEY environment variable is used

# Define your ticker
ticker = "AAPL"

# Define your start year
start_year = 2020

# Initialize start date
start_date = datetime(start_year, 1, 1)

# Define the final end date
final_end_date = datetime(2023, 6, 8)

# Create an empty list to store all the aggs
all_aggs = []

while start_date <= final_end_date:
    # Calculate end date as the last day of the current month
    end_date = start_date + relativedelta(day=31)
    
    # Make sure we don't exceed the specific end date
    end_date = min(end_date, final_end_date)

    # Break the loop if start_date is after the final_end_date
    if start_date > final_end_date:
        break

    # Print status message
    print(f"Fetching data for {ticker} from {start_date.strftime('%Y-%m-%d')} to {end_date.strftime('%Y-%m-%d')}")

    aggs = client.get_aggs(
        ticker,
        1,
        "minute",
        start_date.strftime('%Y-%m-%d'),
        end_date.strftime('%Y-%m-%d'),
    )

    # Add each item in the current month's aggs to the list
    for item in aggs:
        all_aggs.append(item)

    # Increment start_date to the next month
    start_date += relativedelta(months=1)

print(len(all_aggs))

# Print all the aggs at the end
#for aggs in all_aggs:
#    print(aggs)
```

**Comment by KPIyer** [comment]
from polygon.rest worked.

**Comment by justinpolygon** [comment]
Hey @KPIyer, thanks for following up. Also, @MotorCityCobra we have an example now https://github.com/polygon-io/client-python/blob/master/examples/rest/stocks-aggregates_bars.py that supports pagination and you don't need all that extra logic we handle it all. Cheers!

**Comment by alephpt** [comment]
While I appreciate all of the comments here for me it was polygon.rest that made RESTClient available, but then that broke saying there is no Module named pkg_resources 🤔

**Comment by rahul-sh00nya** [comment]
This is not working for `Python 3.12.1`

**Comment by nothingbutadam** [comment]
I have the same issues in Python 3.12.1. Please note I am completely new to python so the following might be completely incorrect. Error message I get is: "ImportError: cannot import name 'RESTClient' from 'polygon'"

In PyCharm if I hover over "polygon" in the code, and then "jump to source" this opens an __init__.py file with the following:

# =========== #
from . import enums
from .base_client import BaseClient, BaseAsyncClient
from .crypto import CryptoClient
from .forex import ForexClient
from .options import (
    OptionsClient,
    build_option_symbol,
    parse_option_symbol,
    OptionSymbol,
    build_polygon_option_symbol,
    parse_polygon_option_symbol,
    convert_option_symbol_formats,
    detect_option_symbol_format,
)
from .reference_apis import ReferenceClient
from .stocks import StocksClient
from .streaming import StreamClient, AsyncStreamClient

# =========== #


__version__ = "1.1.5"

# =========== #


As such, I am making a guess here that "restclient" doesnt exist anymore, and you are meant to choose between baseclient, cryptoclient, forexclient,optionsclient, etc - ie one of the "x"clients mentioned? 

Is that right?

**Comment by adielsa** [comment]
pip install polygon-api-client --force

the --force solve it for me
