### ISSUE TITLE
Configuring DEFAULT_HOST

### ISSUE THREAD

**Issue by rvangundy** [polygon-io/client-python#58]
It doesn't appear that this value is configurable: https://github.com/polygon-io/client-python/blob/ec93d27df053270f8ac01b9871ecf842242c9567/polygon/websocket/websocket_client.py#L13

Am I missing something? Is there an option for using something other than `DEFAULT_HOST`? I would like to use the `delayed` vs. the `socket` websocket endpoint as I am still in earlier evaluation stages with this product.

**Comment by dylanrandle** [comment]
You can simply do `client.DEFAULT_HOST = value` to change it.

**Comment by jpyrett** [comment]
I ran into same issue.  I was expecting to just pass this as argument like the C# shows.   Or just    .HOST    property   instead of DEFAULT_HOST.    Its just not intuitive.

**Comment by matichenor** [comment]
I'm going to wrap this into https://github.com/polygon-io/client-python/issues/53 .  WE plan to implement this feature soon.  Thanks for your suggestion!
