### ISSUE TITLE
Retrieve only the expiration dates for options.

### ISSUE THREAD

**Issue by amaneer94** [polygon-io/client-python#587]
**Is your feature request related to a problem? Please describe.**
Display available expiration dates as a dropdown filter when selecting an underlying ticker.

**Describe the solution you'd like**
Retrieve and present the expiration dates for options as an array of strings for a given underlying ticker.

**Describe alternatives you've considered**
Fetching expiration dates using the Contracts Options API or Snapshot Contract List API is time-consuming as it retrieves all strikes under each expiration date. To optimize, consider a direct approach to obtain only unique expiration dates without fetching redundant strike data.

**Additional context**
I previously utilized the IB Interactive Brokers API, as shown in the attached screenshot, for this purpose. However, I have now transitioned from IB to Polygon, leveraging their advanced subscription.
![image](https://github.com/polygon-io/client-python/assets/16270049/97357316-3c40-4927-978a-e4bcb51b7efb)

**Comment by justinpolygon** [comment]
Hey @amaneer94, thank you for bringing posting this. Your suggestion makes sense and has been forwarded to our backend team for consideration. They'll look into the feasibility and potential integration of your idea into our platform.

This GitHub repository is primarily focused on Python SDK issues, so to keep things organized, I'll be closing this ticket. However, your feature request is being tracked internally with the product team but I can't make any promises about the implementation at this stage.

Thanks again for your contribution!
