### ISSUE TITLE
Can't install on anaconda

### ISSUE THREAD

**Issue by russnagel1** [polygon-io/client-python#59]
I keep getting a packages not found error. Has anyone successfully done this before?

**Comment by dylanrandle** [comment]
It's not available on anaconda. You need to install with `pip`.

**Comment by matichenor** [comment]
After speaking with the development team, this is not something we plan to support at this time.  As Dylan suggestion, you can install via pip:
`pip install polygon-api-client~=1.0.0b`

See the [Getting Started](https://polygon-api-client.readthedocs.io/en/latest/Getting-Started.html) section in our docs or view the [examples](https://github.com/polygon-io/client-python/blob/master/examples) directory.
