### ISSUE TITLE
setuptools is a requirement

### ISSUE THREAD

**Issue by daxm** [polygon-io/client-python#593]
**Describe the bug**
Installing the polygon-api-client Python package does not cover all the underlying reqquirements.  The 'setuptools' package is needed or `from polygon import RESTClient` will fail.

**To Reproduce**
1. `pip uninstall setuptools` <-- Ensure you don't already have setuptools installed.
2. `pip install -U polygon-api-client` <-- Ensure you have the most recent polygon-api-client package.
3. Make a python file with `from polygon import RESTClient` in the file.
4. Run the file and see the error.
5. `pip install setuptools`
6. Run the file and it will run fine.

**Expected behavior**
`setuptools` needs to be in the list of required packages in the published package on pypi for polygon-api-client.

**Screenshots**
```
/home/daxm/PycharmProjects/polygon.io/.venv/bin/python /home/daxm/PycharmProjects/polygon.io/main.py 
Traceback (most recent call last):
  File "/home/daxm/PycharmProjects/polygon.io/main.py", line 4, in <module>
    from polygon import RESTClient
  File "/home/daxm/PycharmProjects/polygon.io/.venv/lib/python3.12/site-packages/polygon/__init__.py", line 1, in <module>
    from .rest import RESTClient
  File "/home/daxm/PycharmProjects/polygon.io/.venv/lib/python3.12/site-packages/polygon/rest/__init__.py", line 1, in <module>
    from .aggs import AggsClient
  File "/home/daxm/PycharmProjects/polygon.io/.venv/lib/python3.12/site-packages/polygon/rest/aggs.py", line 1, in <module>
    from .base import BaseClient
  File "/home/daxm/PycharmProjects/polygon.io/.venv/lib/python3.12/site-packages/polygon/rest/base.py", line 9, in <module>
    import pkg_resources  # part of setuptools
    ^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'pkg_resources'
```

**Comment by justinpolygon** [comment]
Thanks for reporting. I'll check this out.

**Comment by daxm** [comment]
Ah!  I see now.  That is in the "docker run" section... which I wasn't using.  I copy/pasted the docker-compose sections.  Maybe an additional note in that section?

**Comment by justinpolygon** [comment]
> Ah! I see now. That is in the "docker run" section... which I wasn't using. I copy/pasted the docker-compose sections. Maybe an additional note in that section?

@daxm I don't think we mention docker anywhere. Are you using a tutorial? If so can you send me the link.

**Comment by daxm** [comment]
I deleted this message.  Sorry, I'm working on two issues at the same time and posted my response to the other issue here.  :-)

**Comment by justinpolygon** [comment]
Yes, I'll update the readme @bfoz. I'm sorry about that. As you probably read here and in the associated https://github.com/polygon-io/client-python/pull/599 PR, we initially thought it was much more of an edge case, so we added it but really sounds like we should just merge those readme sections. I 100% understand what you're saying and I'll add a PR now,

**Comment by bfoz** [comment]
Thanks, I appreciate the quick response (do you ever take a break? 😀).

Updating the readme is nice, but it turns out that `pip install` can't read the readme, so it doesn't know that it needs to install `setuptools` in situations where it isn't already installed.

**Comment by justinpolygon** [comment]
Yeah, I wonder if we can remove that dependancy. I'll explore the idea. That would be really nice.
