### ISSUE TITLE
Bug in getting stock_equities_condition_mappings - only last value is returned without key

### ISSUE THREAD

**Issue by xpact** [polygon-io/client-python#6]
When you call stock_equities_condition_mappings, the returned resp object is improperly unmarshalled. The call actually returns correct json object but because the returned keys are numbers, which causes the line 49  in definitions.py (function _unmarshal_json_object) to set the attribute_name to empty string. The returned object contains only empty string as key and last value which is "Errored".

**Comment by moilanen** [comment]
Was seeing something similar. This PR #7 fixed it for me.

**Comment by jbonzo** [comment]
#7 has been merged and is current in v0.0.2. If this issue persists we will re-open this issue. Thank you @moilanen for the fix it is much appreciated
