### ISSUE TITLE
Polygon Websocket Hangs Program After Ctrl-C

### ISSUE THREAD

**Issue by dylanrandle** [polygon-io/client-python#60]
Reproduce this by running the [websocket example](https://github.com/polygon-io/client-python/blob/82168a3171d6544ec6d55383c9fc4814dc709658/websocket_example/polygon.py) but change the sleep time to something longer like 60 seconds. After running it for a couple seconds, try to kill the program with `Ctrl-C`. 

For me the data stream stops, but the Python process continues to run and won't exit unless I explicitly kill it.

Culprit here could be [this](https://github.com/polygon-io/client-python/blob/82168a3171d6544ec6d55383c9fc4814dc709658/polygon/websocket/websocket_client.py#L39-L43).

**Comment by matichenor** [comment]
We have released a major update to the python client which I believes addresses this issue.  I could not reproduce the problem with a quick test of the new websocket code.

If you still see an issue, please let us know.

See how to use the new websocket features here:
https://polygon-api-client.readthedocs.io/en/latest/Getting-Started.html#websocket-client-usage
