### ISSUE TITLE
REST Request can be sped up a great deal by keeping an SSL context

### ISSUE THREAD

**Issue by serge-rgb** [polygon-io/client-python#631]
**Describe the bug**

I am developing an app with Polygon as the market data provider. I need to make a high number of REST requests so I use many threads. I noticed a big performance impact so I did some profiling (see screenshot below)

I used a C/C++ profiler, so the Python part of the callstack is obscured, but you can see in the expanded call stack that the app is spending most of its time reading SSL certificate files.

I found a fix that passes a ssl_context to the PoolManager when creating the base client. This greatly increased the performance of the REST client. I'm opening this issue to submit a pull request.

**To Reproduce**

Create a python app that makes many REST requests and look at the CPU usage spike

**Expected behavior**

Better perf

**Screenshots**
![Profiler_aoZobjKaLS](https://github.com/polygon-io/client-python/assets/282970/79fd526b-7096-40b8-b487-a698a2571d4c)

**Comment by serge-rgb** [comment]
Here's a screenshot of the profiler showing the same workload with the fix. 

![Profiler_YJNqnq793E](https://github.com/polygon-io/client-python/assets/282970/e2c29d0d-5061-4032-a6e7-873f3880ba69)

**Comment by justinpolygon** [comment]
This is great @serge-rgb. I'll check it out. Thanks for submitted this with the detailed explanation, plots, and event a patch!

**Comment by justinpolygon** [comment]
Thanks again for contributing this @serge-rgb. We just rolled out a new release with your change https://github.com/polygon-io/client-python/releases/tag/v1.13.5.
