### ISSUE TITLE
from polygon import RESTClient

### ISSUE THREAD

**Issue by vvu1980** [polygon-io/client-python#634]
from polygon import RESTClient 

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[2], line 1
----> 1 from polygon import RESTClient

ImportError: cannot import name 'RESTClient' from 'polygon' (C:\Users\VladV\anaconda3\lib\site-packages\polygon\__init__.py)

**Comment by justinpolygon** [comment]
Hi Vlad, have you run `pip install -U polygon-api-client`?

**Comment by vvu1980** [comment]
Yes, after writing my message I run pip install -U polygon-api-client and everithing is working ok! 
But i did not found how delete my message! 

Sorry!

**Comment by justinpolygon** [comment]
No worries, I'm just happy it's working. I'll close this out.

Also, if you're just getting started we have tons of examples in https://github.com/polygon-io/client-python/tree/master/examples/rest so it's worth checking out.
