### ISSUE TITLE
pypi version is still at 1.13.5

### ISSUE THREAD

**Issue by kartiksubbarao** [polygon-io/client-python#649]
I saw the release announcement for 1.13.6 on github, but pypi is still on 1.13.5:

![image](https://github.com/polygon-io/client-python/assets/134209/738ebe18-8137-40b8-97d1-ac6c8b83fb4d)

**Comment by justinpolygon** [comment]
Yeah, I'm just debugging something with the Github action that seemed break the push to pypi. I'm fixing it now and will retry the push shortly. I'll leave a comment here so you know it's fixed. Sorry about this.

**Comment by kartiksubbarao** [comment]
No probs @justinpolygon, thanks for the quick response!

**Comment by justinpolygon** [comment]
Hey @kartiksubbarao, we have fixed the issue and the releases should be published again. Sorry about that.

**Comment by kartiksubbarao** [comment]
Thanks @justinpolygon
