### ISSUE TITLE
Can't get historical forex quotes to return properly using offset parameter

### ISSUE THREAD

**Issue by enjoysmath** [polygon-io/client-python#66]
```
      with RESTClient(auth_key=os.environ['POLYGON_IO_APIKEY']) as client:
         from_, to = self._asset.split('/')
                  
         last_ts = self._startDatetime.timestamp()
         start_day_str = datetime_day_begin(self._startDatetime).strftime('%Y-%m-%d')
         end_timestamp = self._endDatetime if self._endDatetime else datetime.now()
         end_timestamp = end_timestamp.timestamp()
         print(datetime.fromtimestamp(last_ts))
         print(datetime.fromtimestamp(end_timestamp))
         
         while last_ts < end_timestamp:
            resp = client.forex_currencies_historic_forex_ticks(
               from_, to, start_day_str,
               offset=last_ts, 
               limit1=self._chunkSize)
         
            self._chunkComplete(self._asset, resp.ticks)   
            
            if resp.ticks:
               last_ts = int(resp.ticks[-1]['t'])
               end_timestamp = datetime.now().timestamp()
            else:
               break 
            
         debug_me = True
```

This returns a whole slew of results, but I specified a timestamp offset of practically right this instant.  I printed out the datetimes of the timestamp I'm using and it is indeed right now.

Do you have any idea how to find what the proper parameter names are to pass to the historical forex tick function?

**Comment by enjoysmath** [comment]
Think I found the issue:

![image](https://user-images.githubusercontent.com/1606391/117117533-7e1ad080-ad44-11eb-8309-033baa32e461.png)

See the offset param Wireshark captures.  It's a decimal number.  I'll try converting to milliseconds int.

**Comment by enjoysmath** [comment]
![image](https://user-images.githubusercontent.com/1606391/117117960-039e8080-ad45-11eb-9e78-a1836b4c7b48.png)

This code works, prints nothing!  :D

**Comment by enjoysmath** [comment]
No, that doesn't solve the issue, because you're supposed to multiply by 1000.0 not divide, and when you do that the issue is still there.

**Comment by matichenor** [comment]
Looks like this ticket gathered some dust unfortunately.  If you're still seeing an issue, please raise the problem in the polygon slack or through our web support interface.  

I'll take note for our dev team to improve documentation on handling iterated response values.

**Comment by matichenor** [comment]
Based on this ticket and https://github.com/polygon-io/client-python/issues/71 we are planning to add an iterator object to make these interactions easier.
