### ISSUE TITLE
Inconsistent Type Hinting for Aggregate Date Parameters

### ISSUE THREAD

**Issue by SuperMaZingCoder** [polygon-io/client-python#680]
### Context

[`list_aggs`](https://github.com/polygon-io/client-python/blob/master/polygon/rest/aggs.py#L11) and [`get_aggs`](https://github.com/polygon-io/client-python/blob/master/polygon/rest/aggs.py#L56) type hint `Union[str, int, datetime, date]` for their `from_` and `to` parameters:

```py
from_: Union[str, int, datetime, date],
to: Union[str, int, datetime, date],
```

[`get_grouped_daily_aggs`](https://github.com/polygon-io/client-python/blob/master/polygon/rest/aggs.py#L104) and [`get_daily_open_close_agg`](https://github.com/polygon-io/client-python/blob/master/polygon/rest/aggs.py#L135) only type hint `str` for their `date` parameters:

```py
date: str,
```
___

### Problem: `get_grouped_daily_aggs` and `get_daily_open_close_agg` are missing the type hints they deserve

`datetime.date` objects can already be passed to `get_grouped_daily_aggs` and `get_daily_open_close_agg` since  
```py
f"/v2/aggs/grouped/locale/{locale}/market/{market_type}/{date}"
``` 
and 
```py
f"/v1/open-close/{ticker}/{date}"
```
auto-convert them into strings of `YYYY-MM-DD` format.

This is the same thing that happens in `list_aggs` and `get_aggs`, but they actually get type hinting for `datetime.date` objects. It's a small inconsistency.

Given that it works in all cases, the linting is misleading/inaccurate: 
![image](https://github.com/polygon-io/client-python/assets/55718659/38dfb7f4-1eb6-4bcf-b9d4-316938c7b959)
```
Argument of type "date" cannot be assigned to parameter "date" of type "str" in function "get_daily_open_close_agg" 
"date" is incompatible with "str"
```

___

### Solution

I'm aware neither `get_grouped_daily_aggs` nor `get_daily_open_close_agg` can support `datetime.datetime` objects or UNIX Timestamps since their endpoints don't support it, but type hinting should be added for `datetime.date` objects.

```py
date: Union[str, date],
```
___
It's obviously a very, very small problem, but it's annoying me 😭 A fix would be nice so that `#type: ignore` isn't needed to keep the linter quiet. It's also helpful for people who don't know that string formatting converts `datetime.date` objects into `YYYY-MM-DD` format. 

Super quick fix. I'll have a PR in a few minutes.

**Comment by justinpolygon** [comment]
Great suggestion @SuperMaZingCoder! Thanks for the PR too. I'll merge and we're planning a release shortly so that'll roll out with it. Thank you.
