### ISSUE TITLE
Next page for reference_tickers_v3

### ISSUE THREAD

**Issue by satyan-g** [polygon-io/client-python#71]
The results are limited to 1000. Rest api provides url for next page, how do you use that with python ?

This should probably return an iterator instead of response.

**Comment by brigmecham** [comment]
+1

**Comment by briangu** [comment]
a simple way to use the existing client is:

```
from polygon import RESTClient

all_tickers = []
with RESTClient(key) as client:
    next_url = None
    while True:
        if next_url is None:
            tickers = client.reference_tickers_v3(type="CS")
        else:
            tickers = client._handle_response("ReferenceTickersV3ApiResponse", next_url, {})
        all_tickers.extend(tickers.results)
        if hasattr(tickers, 'next_url'):
            next_url = tickers.next_url
        else:
            break
```

**Comment by matichenor** [comment]
We're planning to add an iterator object to make this use case easier.

**Comment by matichenor** [comment]
We've now released a new python client which includes easy to use `list_*` methods that make paginated results into iterated return objects.

Check it out:
`pip install polygon-api-client~=1.0.0b`

```
from polygon import RESTClient

client = RESTClient()

trades = []
for t in client.list_trades("AAA", "2022-04-04", limit=5):
    trades.append(t)
print(trades)
```

See the [Getting Started](https://polygon-api-client.readthedocs.io/en/latest/Getting-Started.html) section in our docs or view the [examples](https://github.com/polygon-io/client-python/blob/master/examples) directory.
