### ISSUE TITLE
Late and Missing Aggregate Data

### ISSUE THREAD

**Issue by J-B-Blankenship** [polygon-io/client-python#711]
Websocket API: Using the code from #709, `GOOG` will frequently not appear on the minute mark. Code pasted below for repeatability and reference. I cannot tell if this is simply a lack of data or missing data due to current behavior.

REST API: Delays in the data occur ranging upwards of 5+ minutes. A code snippet has been included for repeatability.

Expected Behavior: If this is related to the occurrence of trades (eg. lack thereof), the expectation is the API provides an aggregate with the volume field set to 0; open, low, close, and high repeated from the last aggregate; and timestamps set per usual.

Impact: Aside from unreliable data availability for $200 a month, the models I use require real-time data at 15-minute increments. Any delays of data cause a delay in model decisions which then causes increased market exposure and inaccurate pricing of positions for entries and exits. 3 weeks of internal development time to adapt an MVP to swap from REST API to Websocket API only to find unreliable reporting of data agaom, or lack thereof signal wise of no data. While internal development is not on Polygon, the frustration of spending time to develop a robust solution around the Websocket API for the same issues is immense given the high recommendation from customer service to swap.

Websocket API Code Reproduction:
```
from polygon import WebSocketClient
from polygon.websocket.models import WebSocketMessage

class PolygonAPI:
    def stream_stock_data(
        self,
        symbols: list[str],
    ) -> None:
        websocket = WebSocketClient(api_key=[YOUR_API_KEY], subscriptions=symbols)
        websocket.run(handle_msg=bar)

def bar(
    msg: list[WebSocketMessage]
) -> None:
    for message in msg:
        print(f"symbol: {message.symbol}")

if __name__ == "__main__":
    api = PolygonAPI()
    api.stream_stock_data(symbols=["AM.GOOG", "AM.LCID"])
```

I typed this one in the description, so there may be an error somewhere.
REST API Code Reproduction:
```
import datetime
from multiprocessing import Pool
import time

from polygon import RESTClient
from urllib3.exceptions import MaxRetryError

class PolygonAPI:
    def retrieve_stock_data(
        self,
        symbol: str,
        timeframe: str,
        multiplier: int = 1,
        start: datetime = datetime.now(
            tz=pytz.timezone(Timezone.CST.value)) -
    timedelta(weeks=52 * 2),
        stop: datetime = datetime.now(
            tz=pytz.timezone(Timezone.CST.value)),
        timezone: Timezone = Timezone.CST
    ) -> tuple:
       client = RESTClient(api_key=[YOUR_API_KEY])
       aggregates = []
       try:
           for aggregate in client.list_aggs(
               ticker=symbol,
               multiplier=multiplier,
               timespan=timeframe,
               from_=start.strftime("%Y-%m-%d"),
               to=substop.strftime("%Y-%m-%d"),
               limit=50000):
               aggregates.append(aggregate)

       except MaxRetryError:
           print("Too fast.")
           time.sleep(10)

def call_every_15_minutes(symbol: str) -> None:
    fifteen_minutes_in_seconds = 15 * 60
    api = PolygonAPI()

    last_timestamp = None
    while True:
        aggregates = api.retrieve_stock_data(
            symbol=symbol,
            timespan="minute",
            multiplier=15,
            start=datetime.now() - datetime.timedelta(minutes=30), # Note: This normally uses the last aggregate's timestamp, but I wanted to keep this simple.
            stop=datetime.now() + datetime.timedelta(days=1),
            )

        latest_timestamp = datetime.fromtimestamp(timestamp=aggregates[-1].timestamp / 1000)

        while last_timestamp is not None and latest_timestamp == last_timestamp:
            print("Latest timestamp same as last timestamp")
            print(f"Last Timestamp: {last_timestamp}")
            print(f"Latest Timestamp: {latest_timestamp}")
            time.sleep(1)
            aggregates = api.retrieve_stock_data(
                symbol=symbol,
                timespan="minute",
                multiplier=15,
                start=last_timestamp, # Note: This normally uses the last aggregate's timestamp, but I wanted to keep this simple.
                stop=datetime.now() + datetime.timedelta(days=1),
                )
            latest_timestamp = datetime.fromtimestamp(timestamp=aggregates[-1].timestamp / 1000)

        last_timestamp = latest_timestamp
        time.sleep(fifteen_minutes_in_seconds)

if __name__ == "__main__":
    symbols = ["ADUS", "AMR", "AMWD", "ANF", "BCC", "BOH", "BTU", "CARG", "CUBI", "CNK", "FBP", "GKOS"]

    with Pool() as pool:
        results = pool.map(call_every_15_minutes, symbols)

    for result in results:
        print("Error. Should not be reached.")
```

Please let me know if there are issues with the scripts, but this should replicate the data issue on both APIs.

**Comment by justinpolygon** [comment]
Hey @J-B-Blankenship, was this outside of regular market hours when you were looking at `GOOG`? That might explain why you didn't see an aggregate come through. If there aren't any valid trades, Polygon does not report aggregates with zero volume, so you won't see an aggregate for that period. During regular hours, however, you'll most likely always see them (since there is lots of trading activity). If this issue occurred during regular market hours, could you please add some logging with timestamps and send the log over? That'll help us debug the issue. This approach should clarify why you're not seeing aggregates where you expect them.

**Comment by justinpolygon** [comment]
Just adding a little more context here with an example.

Basically, you'll want to make sure your script or model is aware of this logic. If no valid trades occur within a given minute, which can and often does happen in pre-market and after-hours trading, you might notice gaps in the aggregate data. This happens because we only reports aggregates when there are actual transactions. So, if there were no trades during a specific minute, there won't be any aggregate data for that period, this isn't because things are late or missing, it's just because we have nothing to report on.

**Comment by J-B-Blankenship** [comment]
Fantastic. I know the REST API had real delays for reports in a given time period during normal hours, so those did eventually come through vs. not at all. Websocket API appears to match the outlined behavior, so all set on that front.

Documentation or wording clarification would be fantastic on the site. 

I will try to run the code for the REST API to see if I can snag some timestamps with the symbols provided above. Will be next week after I finish the MVP now that I know the logic and rules to account for no data appropriately for the Websocket API.

**Comment by justinpolygon** [comment]
Great, sounds good. I'll see about adding something to the documentation. Have a good weekend.

**Comment by justinpolygon** [comment]
Hey, I'm going to close this since I believe this was figured out/resolved a while ago.
