### ISSUE TITLE
Access to swagger spec

### ISSUE THREAD

**Issue by SquidSinker** [polygon-io/client-python#78]
Hi, is the swagger spec file for the api available publicly? The README says the clients is generated from "this swagger" but that doesn't seem to be linked anywhere. I could not find a swagger file anywhere in this repo.

**Comment by jbonzo** [comment]
The original swagger that this spec was generated with is no longer available. That was using Swagger v2 and our current documentation is written in OpenAPI spec 3. We have efforts in this quarter to release a v2 of this client library.

Our current spec is available at https://api.polygon.io/openapi

**Comment by SquidSinker** [comment]
Thank you!
