### ISSUE TITLE
no output when running example code

### ISSUE THREAD

**Issue by terekita** [polygon-io/client-python#788]
I just made an account and I'm trying to test the python client in google colab.  After doing the import and setting my key, I try to run the first "AAPL" example. In particular, I run:

```
ticker = "AAPL"

aggs = []
for a in client.list_aggs(ticker=ticker, multiplier=1, timespan="minute", from_="2023-01-01", to="2023-06-13", limit=50000):
    aggs.append(a)

print(aggs)
```

The print statement produces no output. I'm eager to potentially subscribe to this service, but I want to make sure I understand how to use the API first, so any assistance is appreciated, thanks!

**Comment by justinpolygon** [comment]
Hey @terekita, I suspect it's trying to pull down to much data into colab and it's not happy. I'd try and just do a days worth with something like this:

```
for a in client.list_aggs(ticker=ticker, multiplier=1, timespan="minute", from_="2024-11-18", to="2024-11-18", limit=50000):
```

Just to verify that works and then go from there. The API will paginate behind the scenes and pull down all the data so sometimes it might look like it's sitting there doing nothing but it's actually making lots of requests behind the scenes. You can turn on debugging and see all the requests using this:

```
client = RESTClient(trace=True)
```

Cheer! Please let me know how it works out.

**Comment by terekita** [comment]
Thanks for the reply!

When I do:
```
# List Aggregates (Bars)
aggs = []
for a in client.list_aggs(ticker=ticker, multiplier=1, timespan="minute", from_="2024-11-18", to="2024-11-18", limit=50000):
    aggs.append(a)

print(aggs)
```

the print is an empty list: []

This with ticker = "AAPL"

**Comment by justinpolygon** [comment]
Hey @terekita, can you turn on debugging via `client = RESTClient(trace=True)`. I'm just wondering if ticker is actually set. Turning on debugging will give you the API url being called and you can see what's actually being sent.

**Comment by terekita** [comment]
Can't explain why, but everything is working fine now. Seemed like it started working after I turned the debugging on, but that doesn't make sense because I close and reopened a new session and still everything was fine. Thanks!

**Comment by justinpolygon** [comment]
Hey, no worries. I'm just happy its working. Cheers and thanks for letting me know.
