### ISSUE TITLE
incorrect on_close() function skeleton

### ISSUE THREAD

**Issue by amor71** [polygon-io/client-python#85]
Hello,

I noticed that the web-socket client definition typing is:

> def __init__(self, cluster: str, auth_key: str, process_message: Optional[Callable[[str], None]] = None,
>                  on_close: Optional[Callable[[websocket.WebSocketApp], None]] = None,
>                  on_error: Optional[Callable[[websocket.WebSocketApp, str], None]] = None):

However, the proper function skeleton for  `on_close()` is getting two parameters  ( see web-socket client code)

**Comment by matichenor** [comment]
Thanks for raising this issue.  You were paying attention to the details!

We have released a new version of the python client which addresses this issue.  See the [Getting Started](https://polygon-api-client.readthedocs.io/en/latest/Getting-Started.html) section in our docs or view the [examples](https://github.com/polygon-io/client-python/blob/master/examples) directory for install and usage instructions.
