### ISSUE TITLE
Websocket example is not working for crypto

### ISSUE THREAD

**Issue by ben-walczak** [polygon-io/client-python#87]
I successfully subscribed to "XT.X:BTCUSD", but no data is coming in. I only have the currencies subscription, so I do have access to crypto. But no messages come through despite crypto being traded 24/7
![image](https://user-images.githubusercontent.com/25185589/134834412-a46921e6-329c-4b4e-9347-f59a53cd0186.png)

**Comment by dobizz** [comment]
> I successfully subscribed to "XT.X:BTCUSD", but no data is coming in. I only have the currencies subscription, so I do have access to crypto. But no messages come through despite crypto being traded 24/7 ![image](https://user-images.githubusercontent.com/25185589/134834412-a46921e6-329c-4b4e-9347-f59a53cd0186.png)

I think the ticker should have been "XT.BTC-USD"

```my_client.subscribe("XT.BTC-USD")```

![image](https://user-images.githubusercontent.com/12248506/152003290-9d68bfe4-b556-423d-b2a2-f2534118661b.png)

**Comment by matichenor** [comment]
Apologies for the confusion with BTCUSD vs BTC-USD tickers.  I have but a ticket into our engineering team to resolve this confusing behavior.  

In the meantime here is some example code on how to pull websockets using our latest python client.
`from polygon import WebSocketClient
from polygon.websocket.models import WebSocketMessage, Market
from typing import List

# c = WebSocketClient(market=Market.Crypto, subscriptions=["XT.*"])
c = WebSocketClient(market=Market.Crypto, subscriptions=["XT.BTC-USD"])


def handle_msg(msgs: List[WebSocketMessage]):
    for m in msgs:
        print(m)


c.run(handle_msg)`
