### ISSUE TITLE
Missing endpoints

### ISSUE THREAD

**Issue by brigmecham** [polygon-io/client-python#89]
Hello, i can't find the functions and models for some of the v2 endpoints.  In particular the last quote endpoint: /v2/last/nbbo/{stocksTicker}

am I missing something or have they not been included yet?

**Comment by Stormy110** [comment]
Hi there, thank you for reaching out! The Last Trade/Quote are new endpoints that we have yet to add to the Python client. We plan on updating and revamping all of our client SDKs this quarter. Apologies for the inconvenience!

**Comment by matichenor** [comment]
Good news!

All the stock endpoints have now been exposed in the latest version of the client.  To access the updated client, run:
`pip install polygon-api-client~=1.0.0b`

See the [Getting Started](https://polygon-api-client.readthedocs.io/en/latest/Getting-Started.html) section in our docs or view the [examples](https://github.com/polygon-io/client-python/blob/master/examples) directory.

Let us know if you find anything we're missing!
