### ISSUE TITLE
Outdated last_trade endpoint used in method

### ISSUE THREAD

**Issue by willswinson** [polygon-io/client-python#91]
stocks_equities_last_trade_for_a_symbol uses an outdated endpoint that simply returns an error if you try to use it.

Endpoint it uses:
https://api.polygon.io/v1/last/stocks/{symbol}

Updated endpoint:
https://api.polygon.io/v2/last/trade/{symbol}

**Comment by matichenor** [comment]
Closing this ticket to consolidate and track it in https://github.com/polygon-io/client-python/issues/109
