### ISSUE TITLE
How to pass operators like gte to reference_stock_financials

### ISSUE THREAD

**Issue by sameergn** [polygon-io/client-python#94]
This code
`resp = client.reference_stock_financials("AAPL", filing_date.gte="2021-05-01")`
results in compile time error
`Can't assign to function call`

**Comment by matichenor** [comment]
Hi @sameergn , we've made an update in our new python client which makes specifying a "gte" date more straightforward.  

Here's some sample code on how to do it:

```
from polygon import RESTClient

client = RESTClient()

financials = client.vX.list_stock_financials(ticker="AAPL", filing_date_gte="2021-05-01")
for financial in financials:
    print (f"Got financial from polygon: \n{financial}")
```

Read more in the doc here:
https://polygon-api-client.readthedocs.io/en/latest/vX.html

Thanks for raising this issue to our attention! We hope you find the interfaces on the new client more straight forward.  If you have any questions or issues reach out to us.
