### ISSUE TITLE
Full time-span not querying?

### ISSUE THREAD

**Issue by slerman12** [polygon-io/client-python#96]
Hi, I'm trying to run the example except with a longer time span of 2 years and in hourly increments. Instead of returning 2 years of data, the API returns less than 100 hourly data points.

```
with RESTClient(key) as client:
        from_ = datetime.date(2020, 1, 9)
        to = datetime.date(2022, 1, 9)

        resp = client.stocks_equities_aggregates("FB", 1, "hour", from_, to, unadjusted=False)

        print(f"Hour aggregates for {resp.ticker} between {from_} and {to}.")

        for i, result in enumerate(resp.results):
            print(i)
            dt = ts_to_datetime(result["t"])
            print(f"{dt}\n\tO: {result['o']}\n\tH: {result['h']}\n\tL: {result['l']}\n\tC: {result['c']} ")
```

**Comment by secondvibe** [comment]
Have you tried adding the limit parameter?  Max is 50000.

**Comment by matichenor** [comment]
Try adding a high limit value.  Something like:
`resp = client.stocks_equities_aggregates("FB", 1, "hour", from_, to, limit="50000")`

We also plan to add an iterator object to make iterating over a multi-part response easier.
